#!/usr/bin/env python

import BugleChecks

Import('env', 'srcdir', 'builddir')

env.Append(CPPPATH = [srcdir.Dir('platform/null')])

platform_libbugleutils = env.SharedObject(source = [
    'string-null.c',
    'math-null.c',
    'io-null.c',
    'time-null.c'
    ])

platform_libbugle = env.SharedObject(source = [
    'dl-null.c'
    ])

Export('platform_libbugle', 'platform_libbugleutils')
