#!/usr/bin/env python

import BugleChecks

Import('envs', 'srcdir', 'builddir')

env['host'].Append(CPPPATH = [srcdir.Dir('platform/null')])

platform_libbugleutils = envs['host'].SharedObject(source = [
    'string-null.c',
    'math-null.c',
    'io-null.c',
    'time-null.c'
    ])

platform_libbugle = envs['host'].SharedObject(source = [
    'dl-null.c'
    ])

Export('platform_libbugle', 'platform_libbugleutils')
