#!/usr/bin/env python

import BugleChecks

Import('envs', 'srcdir', 'targets')

envs['host'].Append(CPPPATH = [srcdir, Dir('.')],
    LIBS = ['user32', 'kernel32'])

platform_env = envs['host'].Clone()

targets['bugleutils']['source'].extend(platform_env.SharedObject(source = [
    'string-msvcrt.c',
    'math-msvcrt.c',
    # 'io-msvcrt.c',
    'time-msvcrt.c',
    'threads-msvcrt.c',
    '../fallback/bugle_nan.c',
    '../fallback/bugle_strndup.c'
    ]))

targets['bugle']['source'].extend(platform_env.SharedObject(source = [
    'dl-msvcrt.c'
    ]))
