#!/usr/bin/env python

import BugleChecks

Import('envs', 'srcdir', 'builddir', 'targets')

envs['host'].Append(CPPPATH = [
    srcdir.Dir('platform/msvcrt'),
    builddir.Dir('platform/msvcrt')],
    LIBS = ['user32', 'kernel32'])

platform_env = envs['host'].Clone()

targets['bugleutils']['source'].extend(platform_env.SharedObject(source = [
    'string-msvcrt.c',
    'math-msvcrt.c',
    # 'io-msvcrt.c',
    'time-msvcrt.c',
    'threads-msvcrt.c'
    ])

targets['bugle']['source'].extend(platform_env.SharedObject(source = [
    'dl-msvcrt.c'
    ])
