.TH stats_primitives 7 "October 2006" BUGLE "User manual"
.SH NAME
stats_primitives \- gather triangle and batch counts
.SH SYNOPSIS
.nf
filterset stats_primitives
.SH DESCRIPTION
The
.B stats_basic
filter-set provides signals for the number of triangles and batches to
other filter-sets. It must be listed in a chain that uses any
statistics related to triangle or batch counts.
.SH BUGS
Display lists that call other display lists are not handled.

Use of the
.B GL_NV_primitive_restart
extension will yield incorrect results.
.SH AUTHOR
.B gldb
and the
.B bugle
library are written and maintained by Bruce Merry
<bmerry@users.sourceforge.net>.
.SH SEE ALSO
.BR bugle (3),
.BR bugle-stats_basic (3),
.BR bugle-logstats (3),
.BR bugle-showstats (3)
