.TH error 7 "May 2007" BUGLE "User manual"
.SH NAME
showerror \- reports errors in OpenGL calls
.SH SYNOPSIS
.nf
filterset showerror
.fi
.SH DESCRIPTION
This filter-set detects OpenGL errors and writes them to the log (see
.BR bugle-log (7)).
With the default log settings, the error will be reported to standard error.
.SH AUTHOR
.B gldb
and the
.B bugle
library are written and maintained by Bruce Merry
<bmerry@users.sourceforge.net>.
.SH SEE ALSO
.BR bugle (3),
.BR bugle-error (7),
.BR bugle-log (7),
.BR glGetError (3)
