.TH showstats 7 "May 2006" BUGLE "User manual"
.SH NAME
showstats \- render statistics over the display
.SH SYNOPSIS
.nf
filterset frontbuffer
.SH DESCRIPTION
The
.B stats
filter-set gathers statistics about the rendering, such as frame rate.
When this filter-set is also used, the statistics are displayed in the
rendered window.

This filter-set has two parameter,
.BR key_accumulate and key_noaccumulate .
To obtain an average (rather than instantaneous) frame-rate, press the
first key. The frame-rate will then be an average since the key was
pressed. To return to the default display, press the second key.
.SH BUGS
The filter-set has some overhead. You should use the
.B log
filterset to record statistics to file if you want to get accurate
frame-rate measurements.

The triangle and fragment counts are not accumulated.

If the background is white it is impossible to see the statistics.
.SH AUTHOR
.B gldb
and the
.B bugle
library are written and maintained by Bruce Merry
<bmerry@users.sourceforge.net>.
.SH SEE ALSO
.BR bugle (3),
.BR bugle-stats (3)
