.TH stats_nv 7 "October 2006" BUGLE "User manual"
.SH NAME
stats_nv \- gather performance data from NVPerfSDK
.SH SYNOPSIS
.nf
filterset stats_nv
{
    flush "yes"
}
.SH DESCRIPTION
The
.B stats_nv
filter-set extracts data from certain NVIDIA GPUs using NVPerfSDK. This
filter-set is only built if the appropriate header file is present at
compile time, and also requires a suitably configured driver and GPU
(refer to NVPerfSDK documentation). Note that at the time of writing,
NVPerfSDK is not publicly available on any platform supported by BuGLe.

The possible statistics can be seen in the example
.B statistics
file. It is important to read the NVPerfSDK documentation to understand
what the different types of statistics are, what they mean, and the
limitations of the hardware interface.
.SH OPTIONS
.TP
.B flush
If set, a
.BR glFinish (3)
will be issued immediately prior to sampling the counters. This
guarantees that events will be accounted to the correct frame, but will
cause pipeline stalls.
.SH BUGS
Because NVPerfSDK operates across OpenGL contexts, it will count events
from outside the debugged application. In particular, using the
.B showstats
filter-set will bias the statistics.
.SH AUTHOR
.B gldb
and the
.B bugle
library are written and maintained by Bruce Merry
<bmerry@users.sourceforge.net>.
.SH SEE ALSO
.BR bugle (3),
.BR bugle-stats_basic (3),
.BR bugle-logstats (3),
.BR bugle-showstats (3)
