.TH stats_fragments 7 "October 2006" BUGLE "User manual"
.SH NAME
stats_fragments \- gather fragment counts
.SH SYNOPSIS
.nf
filterset stats_fragments
.SH DESCRIPTION
The
.B stats_fragment
filter-set provides signals for the number of fragments to
other filter-sets. It must be listed in a chain that uses any
statistics related to fragment counts.

It is simply a wrapper around
.BR GL_ARB_occlusion_query ,
so a ``fragment'' is defined exactly as in that extension (and OpenGL
1.5), and will not work unless that extension is supported.
.SH BUGS
Fragment counting will not work in applications that use occlusion
queries. A warning is displayed when this condition is detected.
.SH AUTHOR
.B gldb
and the
.B bugle
library are written and maintained by Bruce Merry
<bmerry@users.sourceforge.net>.
.SH SEE ALSO
.BR bugle (3),
.BR bugle-stats_basic (3),
.BR bugle-logstats (3),
.BR bugle-showstats (3)
