#!/usr/bin/env python

Import('envs', 'srcdir', 'builddir', 'aspects', 'libraries')

substs = {
        'GLWIN': aspects['glwin'],
        'GLTYPE': aspects['gltype'],
        'LIBRARIES': ''
        }

for lib in libraries:
    if aspects['binfmt'] == 'pe':
        # TODO need a better way to do this
        mangled = 'c:\\windows\\system32\\' + lib + '.dll'
    else:
        mangled = lib + envs['host'].subst('$SHLIBSUFFIX')
    substs['LIBRARIES'] += 'LIBRARY ' + mangled + '\n'

callapi = aspects['callapi']
if callapi is None or callapi == '':
    substs['CALLAPI'] = ''
else:
    substs['CALLAPI'] = 'CALLAPI ' + callapi

envs['tu'].SubstFile(builddir.File('bc/main.bc'), srcdir.File('bc/main.bc.in'), substs)
