#!/usr/bin/env python

Import('envs', 'srcdir', 'builddir', 'aspects', 'callapi', 'libname')

substs = {
        'GLWIN': aspects['glwin'],
        'GLTYPE': aspects['gltype']
        }
if aspects['binfmt'] == 'pe':
    # TODO need a better way to do this
    substs['LIBNAME'] = 'c:\\windows\\system32\\' + libname + '.dll'
else:
    substs['LIBNAME'] = libname + envs['host'].subst('$SHLIBSUFFIX')

if callapi is None:
    substs['CALLAPI'] = ''
else:
    substs['CALLAPI'] = 'CALLAPI ' + callapi

envs['tu'].SubstFile(builddir.File('bc/main.bc'), srcdir.File('bc/main.bc.in'), substs)
