.TH GLDB 1 "June 2004" BUGLE "User Manual"
.SH NAME
gldb \- Debugger front-end for the BuGLe library
.SH SYNOPSIS
.B gldb
.I prog
.SH DESCRIPTION
.B gldb
is a front-end debugger to be used with the
.BR bugle (3)
library, modelled on
.BR gdb (1).
It can set breakpoints on OpenGL functions, and by default will stop
whenever the program causes a GL error.
.SH COMMANDS
.TP
.B chain \fIname
Specify the name of the filter-set chain to use from the config file
.BR $HOME/.bugle/filters .
If
.I name
is none, then the default (no filters) is used.
.TP
.B help
Show the list of commands, with brief descriptions.
.TP
.B run
Start your program.
.TP
.B continue
Continue running your program.
.TP
.B kill
Kill the running program.
.TP
.B break \fIfunction
Set a breakpoint at
.I function
(an OpenGL function).
.TP
.B break error
Break on OpenGL errors. This is the default.
.TP
.B unbreak \fIfunction
Do not break on
.IR function.
.TP
.B unbreak error
Do not break on OpenGL errors.
.TP
.B quit
Exit
.BR gldb .
.TP
.B backtrace
Call
.BR gdb (1)
to obtain a stack trace.
.SH FILES
.TP
.B $HOME/.bugle/filters
A configuration file for filters. See
.BR bugle (3).
.SH ENVIRONMENT
.TP
.B BUGLE_CHAIN
.TP 
.B BUGLE_DEBUGGER
.TP
.B BUGLE_DEBUGGER_FD_IN
.TP
.B BUGLE_DEBUGGER_FD_OUT
Internal environment variables used to communicate between the debugger
and the library.
.TP
.B LD_PRELOAD
Used internally to force loading of the library.
.SH AUTHOR
.B gldb
and the
.B bugle
library
are written and maintained by Bruce Merry <bmerry@users.sourceforge.net>.
.SH "SEE ALSO"
.BR bugle (3),
.BR gdb (1)
