#!/usr/bin/env python

Import('env')

# Make sure that config.h from this dir is found
gnulib_env = env.Clone()
gnulib_env.Prepend(CPPPATH = ['.'])

gnulib_sources = [
        'xmalloc.c',
        '../gnulib-local/lib/xalloc-die.c',
        'xstrndup.c',
        'xvasprintf.c',
        'xasprintf.c',
        'lock.c',
        'safe-read.c',
        'safe-write.c',
        'full-write.c']

gnulib_shared = []
for i in gnulib_sources:
    gnulib_shared += gnulib_env.SharedObject(i)

Export('gnulib_shared')
