#!/usr/bin/env python

import BugleChecks

def header_checks(env):
    '''
    Checks that will go into the global config.h, and are needed to determine
    what to put in header files.
    '''
    if env.GetOption('help') or env.GetOption('clean'):
        return env

    conf = Configure(env, custom_tests = BugleChecks.tests, config_h = '#/config.h')
    conf.Define('_POSIX_C_SOURCE', '200112L', 'Enable IEEE 1003.1-2001 functionality')
    return conf.Finish()

Import('env')

env.MergeFlags('-I. -pthread')
env = header_checks(env)

platform_shared = env.SharedObject(source = ['string.c'])

Export('platform_shared')
