#!/usr/bin/env python
Import('env')

# TODO source scanner
env.Command(
        'data/gl.tu',
        'data/gl.c',
        'CCACHE_DISABLE=1 $CC $_CPPINCFLAGS -fdump-translation-unit -c $SOURCE && ./mvtu.sh gl.c $TARGET')
