#!/usr/bin/env python
Import('envs', 'targets', 'aspects')

if 'debugger' in aspects['parts']:
    # TODO use a proper pkg-config configuration test
    # TODO add a #define when GTK 2.6+ is available
    # TODO detect gtkglext+glew
    gtk_env = envs['host'].Clone(parse_flags = ['!pkg-config gtk+-2.0 --cflags --libs'])

    # Non-GUI files
    gldb_shared = envs['host'].StaticObject([
        'gldb-common.c',
        'gldb-channels.c'])

    gldb_gui = gtk_env.Program('gldb-gui', [
        'gldb-gui-backtrace.c',
        'gldb-gui-breakpoint.c',
        'gldb-gui-buffer.c',
        'gldb-gui-framebuffer.c',
        'gldb-gui-image.c',
        'gldb-gui-shader.c',
        'gldb-gui-state.c',
        'gldb-gui-target.c',
        'gldb-gui-texture.c',
        'gldb-gui.c',
        gldb_shared], LIBS = [targets['bugleutils'].out, '$LIBS'])

    Install(aspects['bindir'], gldb_gui)
