#!/usr/bin/env python

Import('build_env', 'tu_env')

# Ensure that <config.h> comes from the one in this directory
budgie_env = build_env.Clone()
budgie_env.Prepend(CPPPATH = ['.'])

budgie_env.CXXFile('bcparser.cpp', 'bcparser.yy', YACCFLAGS = '-d --defines=${TARGET.dir}/bcparser.h')
budgie_env.CXXFile('bclexer.cpp', 'bclexer.ll', LEXFLAGS = '-Pbc_yy')
budgie_env.CXXFile('tulexer.cpp', 'tulexer.ll')

budgie_list = budgie_env.Program('budgie', source = [
    'budgie.cpp',
    'tree.cpp',
    'treeutils.cpp',
    'bcparser.cpp',
    'bclexer.cpp',
    'tulexer.cpp'])

tu_env.Append(BUDGIE = budgie_list[0])
