#!/usr/bin/env python

Import('build_env', 'tu_env')

build_env.CXXFile('bcparser.cpp', 'bcparser.yy', YACCFLAGS = '-d --defines=${TARGET.dir}/bcparser.h')
build_env.CXXFile('bclexer.cpp', 'bclexer.ll', LEXFLAGS = '-Pbc_yy')
build_env.CXXFile('tulexer.cpp', 'tulexer.ll')

budgie_list = build_env.Program('budgie', source = [
    'budgie.cpp',
    'tree.cpp',
    'treeutils.cpp',
    'bcparser.cpp',
    'bclexer.cpp',
    'tulexer.cpp'])

tu_env.Append(BUDGIE = budgie_list[0])
