#!/bin/sh
# $Id: gentokens,v 1.1 2004/02/10 18:16:54 bruce Exp $
# The grep pattern removes obsolete extensions that appear defined in
# Mesa 3.4's gl.h, but are never actually defined due to protecting
# #ifndefs, as well as bitfield values which aren't really enumerants.
base='^#define GL_[_A-Z0-9]+'
suffix='[ \t]+0x[0-9A-F]+';
awk "/$base$suffix/"'{printf "GL_TOKEN_NAME(%s)\n", $2;}' \
  /usr/include/GL/glext.h /usr/include/GL/gl.h | sort -r | uniq \
  | egrep -v '(GL_COLOR_TABLE_.*_EXT)|(GL_.*BIT(_[A-Z]+.*)?)\)'
