/*  BuGLe: an OpenGL debugging tool
 *  Copyright (C) 2004  Bruce Merry
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/* Still TODO:
 * - buffer objects
 * - shader objects
 * - program objects
 * - vertex and fragment program objects
 * - query objects
 * - check all the non-global state (e.g. COORD_REPLACE???)
 * - all the image state (texures, color tables, stipple etc)
 * - GetPixelMap (also sort of image-like)
 * - GetMap
 */

#if HAVE_CONFIG_H
# include <config.h>
#endif
#include "src/utils.h"
#include "src/glstate.h"
#include "src/glutils.h"
#include "src/glexts.h"
#include "src/tracker.h"
#include "common/safemem.h"
#include "budgielib/budgieutils.h"
#include <GL/gl.h>
#include <GL/glext.h>
#include <string.h>
#include <limits.h>
#include <assert.h>

#define STATE_NAME(x) #x, x
#define STATE_NAME_EXT(x, ext) #x, x ## ext

/* Flags are divided up as follows:
 * 0-7: fetch function indicator
 * 8-15: multiplexor state
 * 16-23: conditional selection flags
 * 24-31: other
 */
#define STATE_MODE_GLOBAL                0x00000001    /* glGet* */
#define STATE_MODE_ENABLED               0x00000002    /* glIsEnabled */
#define STATE_MODE_TEX_ENV               0x00000003    /* glGetTexEnv */
#define STATE_MODE_TEX_PARAMETER         0x00000004    /* glGetTexParameter */
#define STATE_MODE_TEX_LEVEL_PARAMETER   0x00000005    /* glGetTexLevelParameter */
#define STATE_MODE_TEX_GEN               0x00000006    /* glGetTexGen */
#define STATE_MODE_LIGHT                 0x00000007    /* glGetLight */
#define STATE_MODE_MATERIAL              0x00000008    /* glGetMaterial */
#define STATE_MODE_CLIP_PLANE            0x00000009    /* glGetClipPlane */
#define STATE_MODE_COLOR_TABLE_PARAMETER 0x0000000a    /* glGetColorTableParameter */
#define STATE_MODE_CONVOLUTION_PARAMETER 0x0000000b    /* glGetConvolutionParameter */
#define STATE_MODE_HISTOGRAM_PARAMETER   0x0000000c    /* glGetHistogramParameter */
#define STATE_MODE_MINMAX_PARAMETER      0x0000000d    /* glGetMinmaxParameter */
#define STATE_MODE_VERTEX_ATTRIB         0x0000000e    /* glGetVertexAttrib */
#define STATE_MODE_QUERY                 0x0000000f    /* glGetQuery */
#define STATE_MODE_QUERY_OBJECT          0x00000010    /* glGetQueryObject */
#define STATE_MODE_MASK                  0x000000ff

#define STATE_MULTIPLEX_ACTIVE_TEXTURE   0x00000100    /* Set active texture */
#define STATE_MULTIPLEX_BIND_TEXTURE     0x00000200    /* Set current texture object */

#define STATE_SELECT_NO_CONVOLUTION_1D   0x00010000    /* Ignore for GL_CONVOLUTION_1D */
#define STATE_SELECT_NON_ZERO            0x00020000    /* Ignore if some field is 0 */
#define STATE_SELECT_NO_PROXY            0x00040000    /* Ignore for proxy targets */
#define STATE_SELECT_NO_BLEND_FUNC_SEPARATE 0x00100000 /* Ignore if GL_EXT_blend_func_separate is present */
#define STATE_SELECT_NO_DRAW_BUFFERS     0x00200000    /* Ignore if GL_ARB_draw_buffers is present */

#define STATE_FLAG_FILTER_CONTROL        0x01000000    /* Pass GL_TEXTURE_FILTER_CONTROL */

/* conveniences */
#define STATE_GLOBAL STATE_MODE_GLOBAL
#define STATE_ENABLED STATE_MODE_ENABLED
#define STATE_TEX_ENV (STATE_MODE_TEX_ENV | STATE_MULTIPLEX_ACTIVE_TEXTURE)
#define STATE_TEX_UNIT (STATE_MODE_GLOBAL | STATE_MULTIPLEX_ACTIVE_TEXTURE)
#define STATE_TEX_UNIT_ENABLED (STATE_MODE_ENABLED | STATE_MULTIPLEX_ACTIVE_TEXTURE)
#define STATE_TEX_PARAMETER (STATE_MODE_TEX_PARAMETER | STATE_MULTIPLEX_BIND_TEXTURE)
#define STATE_TEX_LEVEL_PARAMETER (STATE_MODE_TEX_LEVEL_PARAMETER | STATE_MULTIPLEX_BIND_TEXTURE)
#define STATE_TEX_GEN (STATE_MODE_TEX_GEN | STATE_MULTIPLEX_ACTIVE_TEXTURE)
#define STATE_LIGHT STATE_MODE_LIGHT
#define STATE_MATERIAL STATE_MODE_MATERIAL
#define STATE_CLIP_PLANE STATE_MODE_CLIP_PLANE
#define STATE_COLOR_TABLE_PARAMETER STATE_MODE_COLOR_TABLE_PARAMETER
#define STATE_CONVOLUTION_PARAMETER STATE_MODE_CONVOLUTION_PARAMETER
#define STATE_HISTOGRAM_PARAMETER STATE_MODE_HISTOGRAM_PARAMETER
#define STATE_MINMAX_PARAMETER STATE_MODE_MINMAX_PARAMETER
#define STATE_VERTEX_ATTRIB STATE_MODE_VERTEX_ATTRIB
#define STATE_QUERY STATE_MODE_QUERY
#define STATE_QUERY_OBJECT STATE_MODE_QUERY_OBJECT

static const state_info global_state[] =
{
    { STATE_NAME(GL_CURRENT_COLOR), TYPE_8GLdouble, 4, -1, "1.1", STATE_GLOBAL },
#ifdef GL_EXT_secondary_color
    { STATE_NAME_EXT(GL_CURRENT_SECONDARY_COLOR, _EXT), TYPE_8GLdouble, 4, BUGLE_GL_EXT_secondary_color, "1.4", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_CURRENT_INDEX), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_CURRENT_NORMAL), TYPE_8GLdouble, 3, -1, "1.1", STATE_GLOBAL },
#ifdef GL_EXT_fog_coord
    { STATE_NAME_EXT(GL_CURRENT_FOG_COORDINATE, _EXT), TYPE_8GLdouble, 1, BUGLE_GL_EXT_fog_coord, "1.4", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_CURRENT_RASTER_POSITION), TYPE_8GLdouble, 4, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_CURRENT_RASTER_DISTANCE), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_CURRENT_RASTER_COLOR), TYPE_8GLdouble, 4, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_CURRENT_RASTER_INDEX), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_CURRENT_RASTER_POSITION_VALID), TYPE_9GLboolean, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_EDGE_FLAG), TYPE_9GLboolean, 1, -1, "1.1", STATE_GLOBAL },
#ifdef GL_ARB_multitexture
    { STATE_NAME_EXT(GL_CLIENT_ACTIVE_TEXTURE, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_multitexture, "1.3", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_VERTEX_ARRAY), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_VERTEX_ARRAY_SIZE), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_VERTEX_ARRAY_TYPE), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_VERTEX_ARRAY_STRIDE), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_VERTEX_ARRAY_POINTER), TYPE_P6GLvoid, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_NORMAL_ARRAY), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_NORMAL_ARRAY_TYPE), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_NORMAL_ARRAY_STRIDE), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_NORMAL_ARRAY_POINTER), TYPE_P6GLvoid, 1, -1, "1.1", STATE_GLOBAL },
#ifdef GL_EXT_fog_coord
    { STATE_NAME_EXT(GL_FOG_COORDINATE_ARRAY, _EXT), TYPE_9GLboolean, 1, BUGLE_GL_EXT_fog_coord, "1.4", STATE_ENABLED },
    { STATE_NAME_EXT(GL_FOG_COORDINATE_ARRAY_TYPE, _EXT), TYPE_6GLenum, 1, BUGLE_GL_EXT_fog_coord, "1.4", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_FOG_COORDINATE_ARRAY_STRIDE, _EXT), TYPE_5GLint, 1, BUGLE_GL_EXT_fog_coord, "1.4", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_FOG_COORDINATE_ARRAY_POINTER, _EXT), TYPE_P6GLvoid, 1, BUGLE_GL_EXT_fog_coord, "1.4", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_COLOR_ARRAY), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_COLOR_ARRAY_SIZE), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_COLOR_ARRAY_TYPE), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_COLOR_ARRAY_STRIDE), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_COLOR_ARRAY_POINTER), TYPE_P6GLvoid, 1, -1, "1.1", STATE_GLOBAL },
#ifdef GL_EXT_secondary_color
    { STATE_NAME_EXT(GL_SECONDARY_COLOR_ARRAY, _EXT), TYPE_9GLboolean, 1, BUGLE_GL_EXT_fog_coord, "1.4", STATE_ENABLED },
    { STATE_NAME_EXT(GL_SECONDARY_COLOR_ARRAY_SIZE, _EXT), TYPE_5GLint, 1, BUGLE_GL_EXT_fog_coord, "1.4", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_SECONDARY_COLOR_ARRAY_TYPE, _EXT), TYPE_6GLenum, 1, BUGLE_GL_EXT_fog_coord, "1.4", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_SECONDARY_COLOR_ARRAY_STRIDE, _EXT), TYPE_5GLint, 1, BUGLE_GL_EXT_fog_coord, "1.4", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_SECONDARY_COLOR_ARRAY_POINTER, _EXT), TYPE_P6GLvoid, 1, BUGLE_GL_EXT_fog_coord, "1.4", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_INDEX_ARRAY), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_INDEX_ARRAY_TYPE), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_INDEX_ARRAY_STRIDE), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_INDEX_ARRAY_POINTER), TYPE_P6GLvoid, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_EDGE_FLAG_ARRAY), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_EDGE_FLAG_ARRAY_STRIDE), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_EDGE_FLAG_ARRAY_POINTER), TYPE_P6GLvoid, 1, -1, "1.1", STATE_GLOBAL },
#ifdef GL_ARB_vertex_buffer_object
    { STATE_NAME_EXT(GL_ARRAY_BUFFER_BINDING, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_vertex_buffer_object, "1.5", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_VERTEX_ARRAY_BUFFER_BINDING, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_vertex_buffer_object, "1.5", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_NORMAL_ARRAY_BUFFER_BINDING, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_vertex_buffer_object, "1.5", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_COLOR_ARRAY_BUFFER_BINDING, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_vertex_buffer_object, "1.5", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_INDEX_ARRAY_BUFFER_BINDING, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_vertex_buffer_object, "1.5", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_EDGE_FLAG_ARRAY_BUFFER_BINDING, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_vertex_buffer_object, "1.5", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_SECONDARY_COLOR_ARRAY_BUFFER_BINDING, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_vertex_buffer_object, "1.5", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_FOG_COORDINATE_ARRAY_BUFFER_BINDING, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_vertex_buffer_object, "1.5", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_ELEMENT_ARRAY_BUFFER_BINDING, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_vertex_buffer_object, "1.5", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_COLOR_MATRIX), TYPE_8GLdouble, 16, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_MODELVIEW_MATRIX), TYPE_8GLdouble, 16, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_PROJECTION_MATRIX), TYPE_8GLdouble, 16, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_VIEWPORT), TYPE_5GLint, 4, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_DEPTH_RANGE), TYPE_8GLdouble, 2, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_COLOR_MATRIX_STACK_DEPTH), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_MODELVIEW_STACK_DEPTH), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_PROJECTION_STACK_DEPTH), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MATRIX_MODE), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_NORMALIZE), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
#ifdef GL_EXT_rescale_normal
    { STATE_NAME_EXT(GL_RESCALE_NORMAL, _EXT), TYPE_9GLboolean, 1, BUGLE_GL_EXT_rescale_normal, "1.2", STATE_ENABLED },
#endif
    { STATE_NAME(GL_FOG_COLOR), TYPE_8GLdouble, 4, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_FOG_INDEX), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_FOG_DENSITY), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_FOG_START), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_FOG_END), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_FOG_MODE), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_FOG), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
#ifdef GL_EXT_fog_coord
    { STATE_NAME_EXT(GL_FOG_COORDINATE_SOURCE, _EXT), TYPE_6GLenum, 1, BUGLE_GL_EXT_fog_coord, "1.4", STATE_GLOBAL },
#endif
#ifdef GL_EXT_secondary_color
    { STATE_NAME_EXT(GL_COLOR_SUM, _EXT), TYPE_9GLboolean, 1, BUGLE_GL_EXT_secondary_color, "1.4", STATE_ENABLED },
#endif
    { STATE_NAME(GL_SHADE_MODEL), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_LIGHTING), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_COLOR_MATERIAL), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_COLOR_MATERIAL_PARAMETER), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_COLOR_MATERIAL_FACE), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_LIGHT_MODEL_AMBIENT), TYPE_8GLdouble, 4, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_LIGHT_MODEL_LOCAL_VIEWER), TYPE_9GLboolean, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_LIGHT_MODEL_TWO_SIDE), TYPE_9GLboolean, 1, -1, "1.1", STATE_GLOBAL },
#ifdef GL_EXT_separate_specular_color
    { STATE_NAME(GL_LIGHT_MODEL_COLOR_CONTROL), TYPE_6GLenum, 1, BUGLE_GL_EXT_separate_specular_color, "1.2", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_POINT_SIZE), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_POINT_SMOOTH), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
#ifdef GL_ARB_point_sprite
    { STATE_NAME_EXT(GL_POINT_SPRITE, _ARB), TYPE_9GLboolean, 1, -1, "2.0", STATE_ENABLED },
#endif
#ifdef GL_ARB_point_parameters
    { STATE_NAME_EXT(GL_POINT_SIZE_MIN, _ARB), TYPE_8GLdouble, 1, BUGLE_GL_ARB_point_parameters, "1.4", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_POINT_SIZE_MAX, _ARB), TYPE_8GLdouble, 1, BUGLE_GL_ARB_point_parameters, "1.4", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_POINT_FADE_THRESHOLD_SIZE, _ARB), TYPE_8GLdouble, 1, BUGLE_GL_ARB_point_parameters, "1.4", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_POINT_DISTANCE_ATTENUATION, _ARB), TYPE_8GLdouble, 3, BUGLE_GL_ARB_point_parameters, "1.4", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_LINE_WIDTH), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_LINE_SMOOTH), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_LINE_STIPPLE_PATTERN), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_LINE_STIPPLE_REPEAT), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_LINE_STIPPLE), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_CULL_FACE), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_CULL_FACE_MODE), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_FRONT_FACE), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_POLYGON_SMOOTH), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_POLYGON_MODE), TYPE_6GLenum, 2, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_POLYGON_OFFSET_FACTOR), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_POLYGON_OFFSET_UNITS), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_POLYGON_OFFSET_POINT), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_POLYGON_OFFSET_LINE), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_POLYGON_OFFSET_FILL), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_POLYGON_STIPPLE), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
#ifdef GL_ARB_multisample
    { STATE_NAME_EXT(GL_MULTISAMPLE, _ARB), TYPE_9GLboolean, 1, BUGLE_GL_ARB_multisample, "1.3", STATE_ENABLED },
    { STATE_NAME_EXT(GL_SAMPLE_ALPHA_TO_COVERAGE, _ARB), TYPE_9GLboolean, 1, BUGLE_GL_ARB_multisample, "1.3", STATE_ENABLED },
    { STATE_NAME_EXT(GL_SAMPLE_ALPHA_TO_ONE, _ARB), TYPE_9GLboolean, 1, BUGLE_GL_ARB_multisample, "1.3", STATE_ENABLED },
    { STATE_NAME_EXT(GL_SAMPLE_COVERAGE, _ARB), TYPE_9GLboolean, 1, BUGLE_GL_ARB_multisample, "1.3", STATE_ENABLED },
    { STATE_NAME_EXT(GL_SAMPLE_COVERAGE_VALUE, _ARB), TYPE_8GLdouble, 1, BUGLE_GL_ARB_multisample, "1.3", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_SAMPLE_COVERAGE_INVERT, _ARB), TYPE_9GLboolean, 1, BUGLE_GL_ARB_multisample, "1.3", STATE_GLOBAL },
#endif
#ifdef GL_ARB_multitexture
    { STATE_NAME_EXT(GL_ACTIVE_TEXTURE, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_multitexture, "1.3", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_SCISSOR_TEST), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_SCISSOR_BOX), TYPE_5GLint, 4, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_ALPHA_TEST), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_ALPHA_TEST_FUNC), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_ALPHA_TEST_REF), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_STENCIL_TEST), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_STENCIL_FUNC), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_STENCIL_VALUE_MASK), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_STENCIL_REF), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_STENCIL_FAIL), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_STENCIL_PASS_DEPTH_FAIL), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_STENCIL_PASS_DEPTH_PASS), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
#ifdef GL_VERSION_2_0
    { STATE_NAME(GL_STENCIL_BACK_FUNC), TYPE_6GLenum, 1, -1, "2.0", STATE_GLOBAL },
    { STATE_NAME(GL_STENCIL_BACK_VALUE_MASK), TYPE_5GLint, 1, -1, "2.0", STATE_GLOBAL },
    { STATE_NAME(GL_STENCIL_BACK_REF), TYPE_5GLint, 1, -1, "2.0", STATE_GLOBAL },
    { STATE_NAME(GL_STENCIL_BACK_FAIL), TYPE_6GLenum, 1, -1, "2.0", STATE_GLOBAL },
    { STATE_NAME(GL_STENCIL_BACK_PASS_DEPTH_FAIL), TYPE_6GLenum, 1, -1, "2.0", STATE_GLOBAL },
    { STATE_NAME(GL_STENCIL_BACK_PASS_DEPTH_PASS), TYPE_6GLenum, 1, -1, "2.0", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_DEPTH_TEST), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_DEPTH_FUNC), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_BLEND), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
#ifdef GL_EXT_blend_func_separate
    { STATE_NAME_EXT(GL_BLEND_SRC_RGB, _EXT), TYPE_15GLalternateenum, 1, BUGLE_GL_EXT_blend_func_separate, "1.4", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_BLEND_SRC_ALPHA, _EXT), TYPE_15GLalternateenum, 1, BUGLE_GL_EXT_blend_func_separate, "1.4", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_BLEND_DST_RGB, _EXT), TYPE_15GLalternateenum, 1, BUGLE_GL_EXT_blend_func_separate, "1.4", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_BLEND_DST_ALPHA, _EXT), TYPE_15GLalternateenum, 1, BUGLE_GL_EXT_blend_func_separate, "1.4", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_BLEND_SRC), TYPE_15GLalternateenum, 1, -1, "1.1", STATE_GLOBAL | STATE_SELECT_NO_BLEND_FUNC_SEPARATE },
    { STATE_NAME(GL_BLEND_DST), TYPE_15GLalternateenum, 1, -1, "1.1", STATE_GLOBAL | STATE_SELECT_NO_BLEND_FUNC_SEPARATE },
    { "GL_BLEND_EQUATION_RGB", GL_BLEND_EQUATION, TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
#ifdef GL_EXT_blend_equation_separate
    { STATE_NAME_EXT(GL_BLEND_EQUATION_ALPHA, _EXT), TYPE_6GLenum, 1, BUGLE_GL_EXT_blend_equation_separate, "2.0", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_BLEND_COLOR), TYPE_8GLdouble, 4, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_DITHER), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_INDEX_LOGIC_OP), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_COLOR_LOGIC_OP), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
    { STATE_NAME(GL_LOGIC_OP_MODE), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_DRAW_BUFFER), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL | STATE_SELECT_NO_DRAW_BUFFERS},
    { STATE_NAME(GL_INDEX_WRITEMASK), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_COLOR_WRITEMASK), TYPE_9GLboolean, 4, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_DEPTH_WRITEMASK), TYPE_9GLboolean, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_STENCIL_WRITEMASK), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
#ifdef GL_VERSION_2_0
    { STATE_NAME(GL_STENCIL_BACK_WRITEMASK), TYPE_5GLint, 1, -1, "2.0", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_COLOR_CLEAR_VALUE), TYPE_8GLdouble, 4, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_INDEX_CLEAR_VALUE), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_DEPTH_CLEAR_VALUE), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_STENCIL_CLEAR_VALUE), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_ACCUM_CLEAR_VALUE), TYPE_8GLdouble, 4, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_UNPACK_SWAP_BYTES), TYPE_9GLboolean, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_UNPACK_LSB_FIRST), TYPE_9GLboolean, 1, -1, "1.1", STATE_GLOBAL },
#ifdef GL_EXT_texture3D
    { STATE_NAME_EXT(GL_UNPACK_IMAGE_HEIGHT, _EXT), TYPE_5GLint, 1, BUGLE_GL_EXT_texture3D, "1.2", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_UNPACK_SKIP_IMAGES, _EXT), TYPE_5GLint, 1, BUGLE_GL_EXT_texture3D, "1.2", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_UNPACK_ROW_LENGTH), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_UNPACK_SKIP_ROWS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_UNPACK_SKIP_PIXELS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_UNPACK_ALIGNMENT), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_PACK_SWAP_BYTES), TYPE_9GLboolean, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_PACK_LSB_FIRST), TYPE_9GLboolean, 1, -1, "1.1", STATE_GLOBAL },
#ifdef GL_EXT_texture3D
    { STATE_NAME_EXT(GL_PACK_IMAGE_HEIGHT, _EXT), TYPE_5GLint, 1, BUGLE_GL_EXT_texture3D, "1.2", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_PACK_SKIP_IMAGES, _EXT), TYPE_5GLint, 1, BUGLE_GL_EXT_texture3D, "1.2", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_PACK_ROW_LENGTH), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_PACK_SKIP_ROWS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_PACK_SKIP_PIXELS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_PACK_ALIGNMENT), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MAP_COLOR), TYPE_9GLboolean, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MAP_STENCIL), TYPE_9GLboolean, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_INDEX_SHIFT), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_INDEX_OFFSET), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_RED_SCALE), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_GREEN_SCALE), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_BLUE_SCALE), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_ALPHA_SCALE), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_DEPTH_SCALE), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_RED_BIAS), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_GREEN_BIAS), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_BLUE_BIAS), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_ALPHA_BIAS), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_DEPTH_BIAS), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_COLOR_TABLE), TYPE_9GLboolean, 1, BUGLE_GL_ARB_imaging, NULL, STATE_ENABLED },
    { STATE_NAME(GL_POST_CONVOLUTION_COLOR_TABLE), TYPE_9GLboolean, 1, BUGLE_GL_ARB_imaging, NULL, STATE_ENABLED },
    { STATE_NAME(GL_POST_COLOR_MATRIX_COLOR_TABLE), TYPE_9GLboolean, 1, BUGLE_GL_ARB_imaging, NULL, STATE_ENABLED },
    /* Note: images missing here */
    { STATE_NAME(GL_POST_CONVOLUTION_RED_SCALE), TYPE_8GLdouble, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_POST_CONVOLUTION_GREEN_SCALE), TYPE_8GLdouble, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_POST_CONVOLUTION_BLUE_SCALE), TYPE_8GLdouble, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_POST_CONVOLUTION_ALPHA_SCALE), TYPE_8GLdouble, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_POST_CONVOLUTION_RED_BIAS), TYPE_8GLdouble, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_POST_CONVOLUTION_GREEN_BIAS), TYPE_8GLdouble, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_POST_CONVOLUTION_BLUE_BIAS), TYPE_8GLdouble, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_POST_CONVOLUTION_ALPHA_BIAS), TYPE_8GLdouble, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_POST_COLOR_MATRIX_RED_SCALE), TYPE_8GLdouble, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_POST_COLOR_MATRIX_GREEN_SCALE), TYPE_8GLdouble, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_POST_COLOR_MATRIX_BLUE_SCALE), TYPE_8GLdouble, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_POST_COLOR_MATRIX_ALPHA_SCALE), TYPE_8GLdouble, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_POST_COLOR_MATRIX_RED_BIAS), TYPE_8GLdouble, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_POST_COLOR_MATRIX_GREEN_BIAS), TYPE_8GLdouble, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_POST_COLOR_MATRIX_BLUE_BIAS), TYPE_8GLdouble, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_POST_COLOR_MATRIX_ALPHA_BIAS), TYPE_8GLdouble, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_HISTOGRAM), TYPE_9GLboolean, 1, BUGLE_GL_ARB_imaging, NULL, STATE_ENABLED },
    { STATE_NAME(GL_MINMAX), TYPE_9GLboolean, 1, BUGLE_GL_ARB_imaging, NULL, STATE_ENABLED },
    { STATE_NAME(GL_ZOOM_X), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_ZOOM_Y), TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    /* FIXME: GetPixelMap state missing here */
    { STATE_NAME(GL_READ_BUFFER), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    /* FIXME: pixel map state missing here */
    { STATE_NAME(GL_MAP1_GRID_DOMAIN), TYPE_8GLdouble, 2, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MAP2_GRID_DOMAIN), TYPE_8GLdouble, 4, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MAP1_GRID_SEGMENTS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MAP2_GRID_SEGMENTS), TYPE_5GLint, 2, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_AUTO_NORMAL), TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED },
#ifdef GL_VERSION_2_0
    { STATE_NAME(GL_CURRENT_PROGRAM), TYPE_5GLint, 1, -1, "2.0", STATE_GLOBAL },
#endif
#ifdef GL_ARB_vertex_program
    { STATE_NAME_EXT(GL_VERTEX_PROGRAM_TWO_SIDE, _ARB), TYPE_9GLboolean, 1, BUGLE_GL_ARB_vertex_program, "2.0", STATE_ENABLED },
    { STATE_NAME_EXT(GL_VERTEX_PROGRAM_POINT_SIZE, _ARB), TYPE_9GLboolean, 1, BUGLE_GL_ARB_vertex_program, "2.0", STATE_ENABLED },
#endif
    { STATE_NAME(GL_PERSPECTIVE_CORRECTION_HINT), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_POINT_SMOOTH_HINT), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_LINE_SMOOTH_HINT), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_POLYGON_SMOOTH_HINT), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_FOG_HINT), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
#ifdef GL_SGIS_generate_mipmap
    { STATE_NAME_EXT(GL_GENERATE_MIPMAP_HINT, _SGIS), TYPE_6GLenum, 1, BUGLE_GL_SGIS_generate_mipmap, "1.4", STATE_GLOBAL },
#endif
#ifdef GL_ARB_texture_compression
    { STATE_NAME_EXT(GL_TEXTURE_COMPRESSION_HINT, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_texture_compression, "1.3", STATE_GLOBAL },
#endif
    /* NVIDIA ship a glext.h that doesn't define GL_FRAGMENT_SHADER_DERIVATIVE_HINT_ARB */
#if defined(GL_ARB_fragment_shader) && defined(GL_FRAGMENT_SHADER_DERIVATIVE_HINT_ARB)
    { STATE_NAME_EXT(GL_FRAGMENT_SHADER_DERIVATIVE_HINT, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_fragment_program, "2.0", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_MAX_LIGHTS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MAX_CLIP_PLANES), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MAX_COLOR_MATRIX_STACK_DEPTH), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_GLOBAL },
    { STATE_NAME(GL_MAX_MODELVIEW_STACK_DEPTH), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MAX_PROJECTION_STACK_DEPTH), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MAX_TEXTURE_STACK_DEPTH), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_SUBPIXEL_BITS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
#ifdef GL_EXT_texture3D
    { STATE_NAME_EXT(GL_MAX_3D_TEXTURE_SIZE, _EXT), TYPE_5GLint, 1, BUGLE_GL_EXT_texture3D, "1.2", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_MAX_TEXTURE_SIZE), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
#ifdef GL_EXT_texture_lod_bias
    { STATE_NAME_EXT(GL_MAX_TEXTURE_LOD_BIAS, _EXT), TYPE_8GLdouble, 1, BUGLE_GL_EXT_texture_lod_bias, "1.4", STATE_GLOBAL },
#endif
#ifdef GL_ARB_texture_cube_map
    { STATE_NAME_EXT(GL_MAX_CUBE_MAP_TEXTURE_SIZE, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_texture_cube_map, "1.3", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_MAX_PIXEL_MAP_TABLE), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MAX_NAME_STACK_DEPTH), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MAX_LIST_NESTING), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MAX_EVAL_ORDER), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MAX_VIEWPORT_DIMS), TYPE_5GLint, 2, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MAX_ATTRIB_STACK_DEPTH), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MAX_CLIENT_ATTRIB_STACK_DEPTH), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_AUX_BUFFERS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_RGBA_MODE), TYPE_9GLboolean, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_INDEX_MODE), TYPE_9GLboolean, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_DOUBLEBUFFER), TYPE_9GLboolean, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_STEREO), TYPE_9GLboolean, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_ALIASED_POINT_SIZE_RANGE), TYPE_8GLdouble, 2, -1, "1.2", STATE_GLOBAL },
    { "GL_SMOOTH_POINT_SIZE_RANGE", GL_POINT_SIZE_RANGE, TYPE_8GLdouble, 2, -1, "1.1", STATE_GLOBAL },
    { "GL_SMOOTH_POINT_SIZE_GRANULARITY", GL_POINT_SIZE_GRANULARITY, TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_ALIASED_LINE_WIDTH_RANGE), TYPE_8GLdouble, 2, -1, "1.2", STATE_GLOBAL },
    { "GL_SMOOTH_LINE_WIDTH_RANGE", GL_LINE_WIDTH_RANGE, TYPE_8GLdouble, 2, -1, "1.1", STATE_GLOBAL },
    { "GL_SMOOTH_LINE_WIDTH_GRANULARITY", GL_LINE_WIDTH_GRANULARITY, TYPE_8GLdouble, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MAX_ELEMENTS_INDICES), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_MAX_ELEMENTS_VERTICES), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
#ifdef GL_ARB_multitexture
    { STATE_NAME_EXT(GL_MAX_TEXTURE_UNITS, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_multitexture, "1.3", STATE_GLOBAL },
#endif
#ifdef GL_ARB_multisample
    { STATE_NAME_EXT(GL_SAMPLE_BUFFERS, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_multisample, "1.3", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_SAMPLES, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_multisample, "1.3", STATE_GLOBAL },
#endif
#ifdef GL_ARB_texture_compression
    { STATE_NAME_EXT(GL_NUM_COMPRESSED_TEXTURE_FORMATS, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_texture_compression, "1.3", STATE_GLOBAL },
#endif
    /* FIXME: QUERY_COUNTER_BITS missing? */
    { STATE_NAME(GL_EXTENSIONS), TYPE_PKc, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_RENDERER), TYPE_PKc, 1, -1, "1.1", STATE_GLOBAL },
    /* SHADING_LANGUAGE_VERSION was only added in a later version of the spec */
#if defined(GL_ARB_shading_language_100) && defined(GL_SHADING_LANGUAGE_VERSION_ARB)
    { STATE_NAME_EXT(GL_SHADING_LANGUAGE_VERSION, _ARB), TYPE_PKc, 1, BUGLE_GL_ARB_shading_language_100, "2.0", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_VENDOR), TYPE_PKc, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_VERSION), TYPE_PKc, 1, -1, "1.1", STATE_GLOBAL },
#ifdef GL_ARB_vertex_program
    { STATE_NAME_EXT(GL_MAX_VERTEX_ATTRIBS, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_vertex_program, "2.0", STATE_GLOBAL },
#endif
#ifdef GL_ARB_vertex_shader
    { STATE_NAME_EXT(GL_MAX_VERTEX_UNIFORM_COMPONENTS, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_vertex_shader, "2.0", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_MAX_VARYING_FLOATS, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_vertex_shader, "2.0", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_vertex_shader, "2.0", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_vertex_shader, "2.0", STATE_GLOBAL },
#endif
#ifdef GL_ARB_fragment_program
    { STATE_NAME_EXT(GL_MAX_TEXTURE_IMAGE_UNITS, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_fragment_program, "2.0", STATE_GLOBAL },
    { STATE_NAME_EXT(GL_MAX_TEXTURE_COORDS, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_fragment_program, "2.0", STATE_GLOBAL },
#endif
#ifdef GL_ARB_fragment_shader
    { STATE_NAME_EXT(GL_MAX_FRAGMENT_UNIFORM_COMPONENTS, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_fragment_shader, "2.0", STATE_GLOBAL },
#endif
    /* Note: The GL 2.0 spec duplicate some entries at this point */
#ifdef GL_ARB_draw_buffers
    { STATE_NAME_EXT(GL_MAX_DRAW_BUFFERS, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_draw_buffers, "2.0", STATE_GLOBAL },
#endif
    { STATE_NAME(GL_RED_BITS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_GREEN_BITS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_BLUE_BITS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_ALPHA_BITS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_INDEX_BITS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_DEPTH_BITS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_STENCIL_BITS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_ACCUM_RED_BITS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_ACCUM_GREEN_BITS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_ACCUM_BLUE_BITS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_ACCUM_ALPHA_BITS), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_LIST_BASE), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_LIST_INDEX), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_LIST_MODE), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_ATTRIB_STACK_DEPTH), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_CLIENT_ATTRIB_STACK_DEPTH), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_NAME_STACK_DEPTH), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_RENDER_MODE), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_SELECTION_BUFFER_POINTER), TYPE_P6GLvoid, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_SELECTION_BUFFER_SIZE), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_FEEDBACK_BUFFER_POINTER), TYPE_P6GLvoid, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_FEEDBACK_BUFFER_SIZE), TYPE_5GLint, 1, -1, "1.1", STATE_GLOBAL },
    { STATE_NAME(GL_FEEDBACK_BUFFER_TYPE), TYPE_6GLenum, 1, -1, "1.1", STATE_GLOBAL },
    /* FIXME: missing GL_QUERY_CURRENT */
    { NULL, GL_NONE, NULL_TYPE, 0, 0, NULL, 0 }
};

static const state_info tex_parameter_state[] =
{
    { STATE_NAME(GL_TEXTURE_BORDER_COLOR), TYPE_8GLdouble, 4, -1, "1.1", STATE_TEX_PARAMETER },
    { STATE_NAME(GL_TEXTURE_MIN_FILTER), TYPE_6GLenum, 1, -1, "1.1", STATE_TEX_PARAMETER },
    { STATE_NAME(GL_TEXTURE_MAG_FILTER), TYPE_6GLenum, 1, -1, "1.1", STATE_TEX_PARAMETER },
    { STATE_NAME(GL_TEXTURE_WRAP_S), TYPE_6GLenum, 1, -1, "1.1", STATE_TEX_PARAMETER },
    { STATE_NAME(GL_TEXTURE_WRAP_T), TYPE_6GLenum, 1, -1, "1.1", STATE_TEX_PARAMETER },
    { STATE_NAME(GL_TEXTURE_WRAP_R), TYPE_6GLenum, 1, -1, "1.1", STATE_TEX_PARAMETER },
    { STATE_NAME(GL_TEXTURE_PRIORITY), TYPE_8GLdouble, 1, -1, "1.1", STATE_TEX_PARAMETER },
    { STATE_NAME(GL_TEXTURE_RESIDENT), TYPE_9GLboolean, 1, -1, "1.1", STATE_TEX_PARAMETER },
#ifdef GL_SGIS_texture_lod
    { STATE_NAME_EXT(GL_TEXTURE_MIN_LOD, _SGIS), TYPE_8GLdouble, 1, BUGLE_GL_SGIS_texture_lod, "1.2", STATE_TEX_PARAMETER },
    { STATE_NAME_EXT(GL_TEXTURE_MAX_LOD, _SGIS), TYPE_8GLdouble, 1, BUGLE_GL_SGIS_texture_lod, "1.2", STATE_TEX_PARAMETER },
    { STATE_NAME_EXT(GL_TEXTURE_BASE_LEVEL, _SGIS), TYPE_5GLint, 1, BUGLE_GL_SGIS_texture_lod, "1.2", STATE_TEX_PARAMETER },
    { STATE_NAME_EXT(GL_TEXTURE_MAX_LEVEL, _SGIS), TYPE_5GLint, 1, BUGLE_GL_SGIS_texture_lod, "1.2", STATE_TEX_PARAMETER },
#endif
#ifdef GL_EXT_texture_lod_bias
    { STATE_NAME_EXT(GL_TEXTURE_LOD_BIAS, _EXT), TYPE_8GLdouble, 1, BUGLE_GL_EXT_texture_lod_bias, "1.4", STATE_TEX_PARAMETER },
#endif
#ifdef GL_ARB_depth_texture
    { STATE_NAME_EXT(GL_DEPTH_TEXTURE_MODE, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_depth_texture, "1.4", STATE_TEX_PARAMETER },
#endif
#ifdef GL_ARB_shadow
    { STATE_NAME_EXT(GL_TEXTURE_COMPARE_MODE, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_shadow, "1.4", STATE_TEX_PARAMETER },
    { STATE_NAME_EXT(GL_TEXTURE_COMPARE_FUNC, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_shadow, "1.4", STATE_TEX_PARAMETER },
#endif
#ifdef GL_SGIS_generate_mipmap
    { STATE_NAME_EXT(GL_GENERATE_MIPMAP, _SGIS), TYPE_9GLboolean, 1, BUGLE_GL_SGIS_generate_mipmap, "1.4", STATE_TEX_PARAMETER },
#endif
    { NULL, GL_NONE, NULL_TYPE, 0, 0, NULL, 0 }
};

static const state_info tex_level_parameter_state[] =
{
    { STATE_NAME(GL_TEXTURE_WIDTH), TYPE_5GLint, 1, -1, "1.1", STATE_TEX_LEVEL_PARAMETER },
    { STATE_NAME(GL_TEXTURE_HEIGHT), TYPE_5GLint, 1, -1, "1.1", STATE_TEX_LEVEL_PARAMETER },
#ifdef GL_EXT_texture3D
    { STATE_NAME_EXT(GL_TEXTURE_DEPTH, _EXT), TYPE_5GLint, 1, BUGLE_GL_EXT_texture3D, "1.2", STATE_TEX_LEVEL_PARAMETER },
#endif
    { STATE_NAME(GL_TEXTURE_BORDER), TYPE_5GLint, 1, -1, "1.1", STATE_TEX_LEVEL_PARAMETER },
    { STATE_NAME(GL_TEXTURE_INTERNAL_FORMAT), TYPE_16GLcomponentsenum, 1, -1, "1.1", STATE_TEX_LEVEL_PARAMETER },
    { STATE_NAME(GL_TEXTURE_RED_SIZE), TYPE_5GLint, 1, -1, "1.1", STATE_TEX_LEVEL_PARAMETER },
    { STATE_NAME(GL_TEXTURE_GREEN_SIZE), TYPE_5GLint, 1, -1, "1.1", STATE_TEX_LEVEL_PARAMETER },
    { STATE_NAME(GL_TEXTURE_BLUE_SIZE), TYPE_5GLint, 1, -1, "1.1", STATE_TEX_LEVEL_PARAMETER },
    { STATE_NAME(GL_TEXTURE_ALPHA_SIZE), TYPE_5GLint, 1, -1, "1.1", STATE_TEX_LEVEL_PARAMETER },
    { STATE_NAME(GL_TEXTURE_LUMINANCE_SIZE), TYPE_5GLint, 1, -1, "1.1", STATE_TEX_LEVEL_PARAMETER },
    { STATE_NAME(GL_TEXTURE_INTENSITY_SIZE), TYPE_5GLint, 1, -1, "1.1", STATE_TEX_LEVEL_PARAMETER },
#ifdef GL_ARB_depth_texture
    { STATE_NAME_EXT(GL_TEXTURE_DEPTH_SIZE, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_depth_texture, "1.4", STATE_TEX_LEVEL_PARAMETER },
#endif
#ifdef GL_ARB_texture_compression
    { STATE_NAME_EXT(GL_TEXTURE_COMPRESSED, _ARB), TYPE_9GLboolean, 1, BUGLE_GL_ARB_texture_compression, "1.3", STATE_TEX_LEVEL_PARAMETER },
#endif
    { NULL, GL_NONE, NULL_TYPE, 0, 0, NULL, 0 }
};

static const state_info tex_unit_state[] =
{
    { STATE_NAME(GL_TEXTURE_COORD_ARRAY), TYPE_9GLboolean, 1, -1, "1.1", STATE_TEX_UNIT_ENABLED },
    { STATE_NAME(GL_TEXTURE_COORD_ARRAY_SIZE), TYPE_5GLint, 1, -1, "1.1", STATE_TEX_UNIT },
    { STATE_NAME(GL_TEXTURE_COORD_ARRAY_TYPE), TYPE_6GLenum, 1, -1, "1.1", STATE_TEX_UNIT },
    { STATE_NAME(GL_TEXTURE_COORD_ARRAY_STRIDE), TYPE_5GLint, 1, -1, "1.1", STATE_TEX_UNIT },
    { STATE_NAME(GL_TEXTURE_COORD_ARRAY_POINTER), TYPE_P6GLvoid, 1, -1, "1.1", STATE_TEX_UNIT },
    { STATE_NAME(GL_TEXTURE_ENV_MODE), TYPE_6GLenum, 1, -1, "1.1", STATE_TEX_ENV },
    { STATE_NAME(GL_TEXTURE_ENV_COLOR), TYPE_8GLdouble, 4, -1, "1.1", STATE_TEX_ENV },
#ifdef GL_EXT_texture_lod_bias
    { STATE_NAME_EXT(GL_TEXTURE_LOD_BIAS, _EXT), TYPE_8GLdouble, 1, BUGLE_GL_EXT_texture_lod_bias, "1.4", STATE_TEX_ENV | STATE_FLAG_FILTER_CONTROL },
#endif
#ifdef GL_EXT_texture_env_combine
    { STATE_NAME_EXT(GL_COMBINE_RGB, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_texture_env_combine, "1.3", STATE_TEX_ENV },
    { STATE_NAME_EXT(GL_COMBINE_ALPHA, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_texture_env_combine, "1.3", STATE_TEX_ENV },
    { STATE_NAME_EXT(GL_SOURCE0_RGB, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_texture_env_combine, "1.3", STATE_TEX_ENV },
    { STATE_NAME_EXT(GL_SOURCE1_RGB, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_texture_env_combine, "1.3", STATE_TEX_ENV },
    { STATE_NAME_EXT(GL_SOURCE2_RGB, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_texture_env_combine, "1.3", STATE_TEX_ENV },
    { STATE_NAME_EXT(GL_SOURCE0_ALPHA, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_texture_env_combine, "1.3", STATE_TEX_ENV },
    { STATE_NAME_EXT(GL_SOURCE1_ALPHA, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_texture_env_combine, "1.3", STATE_TEX_ENV },
    { STATE_NAME_EXT(GL_SOURCE2_ALPHA, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_texture_env_combine, "1.3", STATE_TEX_ENV },
    { STATE_NAME_EXT(GL_OPERAND0_RGB, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_texture_env_combine, "1.3", STATE_TEX_ENV },
    { STATE_NAME_EXT(GL_OPERAND1_RGB, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_texture_env_combine, "1.3", STATE_TEX_ENV },
    { STATE_NAME_EXT(GL_OPERAND2_RGB, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_texture_env_combine, "1.3", STATE_TEX_ENV },
    { STATE_NAME_EXT(GL_OPERAND0_ALPHA, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_texture_env_combine, "1.3", STATE_TEX_ENV },
    { STATE_NAME_EXT(GL_OPERAND1_ALPHA, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_texture_env_combine, "1.3", STATE_TEX_ENV },
    { STATE_NAME_EXT(GL_OPERAND2_ALPHA, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_texture_env_combine, "1.3", STATE_TEX_ENV },
    { STATE_NAME_EXT(GL_RGB_SCALE, _ARB), TYPE_8GLdouble, 1, BUGLE_GL_ARB_texture_env_combine, "1.3", STATE_TEX_ENV },
    { STATE_NAME(GL_ALPHA_SCALE), TYPE_8GLdouble, 1, BUGLE_GL_ARB_texture_env_combine, "1.3", STATE_TEX_ENV },
#endif
    { STATE_NAME(GL_CURRENT_TEXTURE_COORDS), TYPE_8GLdouble, 4, -1, "1.1", STATE_TEX_UNIT },
    { STATE_NAME(GL_CURRENT_RASTER_TEXTURE_COORDS), TYPE_8GLdouble, 4, -1, "1.1", STATE_TEX_UNIT },
    { STATE_NAME(GL_TEXTURE_MATRIX), TYPE_8GLdouble, 16, -1, "1.1", STATE_TEX_UNIT },
    { STATE_NAME(GL_TEXTURE_STACK_DEPTH), TYPE_5GLint, 1, -1, "1.1", STATE_TEX_UNIT },
    { STATE_NAME(GL_TEXTURE_1D), TYPE_9GLboolean, 1, -1, "1.1", STATE_TEX_UNIT_ENABLED },
    { STATE_NAME(GL_TEXTURE_2D), TYPE_9GLboolean, 1, -1, "1.1", STATE_TEX_UNIT_ENABLED },
#ifdef GL_EXT_texture3D
    { STATE_NAME_EXT(GL_TEXTURE_3D, _EXT), TYPE_9GLboolean, 1, BUGLE_GL_EXT_texture3D, "1.2", STATE_TEX_UNIT_ENABLED },
#endif
#ifdef GL_ARB_texture_cube_map
    { STATE_NAME_EXT(GL_TEXTURE_CUBE_MAP, _ARB), TYPE_9GLboolean, 1, BUGLE_GL_ARB_texture_cube_map, "1.3", STATE_TEX_UNIT_ENABLED },
#endif
    { STATE_NAME(GL_TEXTURE_BINDING_1D), TYPE_5GLint, 1, -1, "1.1", STATE_TEX_UNIT },
    { STATE_NAME(GL_TEXTURE_BINDING_2D), TYPE_5GLint, 1, -1, "1.1", STATE_TEX_UNIT },
#ifdef GL_VERSION_1_2
    { STATE_NAME(GL_TEXTURE_BINDING_3D), TYPE_5GLint, 1, -1, "1.2", STATE_TEX_UNIT }, /* Note: GL_EXT_texture3D doesn't define this! */
#endif
#ifdef GL_ARB_texture_cube_map
    { STATE_NAME_EXT(GL_TEXTURE_BINDING_CUBE_MAP, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_texture_cube_map, "1.3", STATE_TEX_UNIT },
#endif
    { STATE_NAME(GL_TEXTURE_GEN_S), TYPE_9GLboolean, 1, -1, "1.1", STATE_TEX_UNIT_ENABLED },
    { STATE_NAME(GL_TEXTURE_GEN_T), TYPE_9GLboolean, 1, -1, "1.1", STATE_TEX_UNIT_ENABLED },
    { STATE_NAME(GL_TEXTURE_GEN_R), TYPE_9GLboolean, 1, -1, "1.1", STATE_TEX_UNIT_ENABLED },
    { STATE_NAME(GL_TEXTURE_GEN_Q), TYPE_9GLboolean, 1, -1, "1.1", STATE_TEX_UNIT_ENABLED },
    { NULL, GL_NONE, NULL_TYPE, 0, 0, NULL, 0 }
};

static const state_info tex_gen_state[] =
{
    { STATE_NAME(GL_EYE_PLANE), TYPE_8GLdouble, 4, -1, "1.1", STATE_TEX_GEN },
    { STATE_NAME(GL_OBJECT_PLANE), TYPE_8GLdouble, 4, -1, "1.1", STATE_TEX_GEN },
    { STATE_NAME(GL_TEXTURE_GEN_MODE), TYPE_6GLenum, 1, -1, "1.1", STATE_TEX_GEN },
    { NULL, GL_NONE, NULL_TYPE, 0, 0, NULL, 0 }
};

static const state_info light_state[] =
{
    { STATE_NAME(GL_AMBIENT), TYPE_8GLdouble, 4, -1, "1.1", STATE_LIGHT },
    { STATE_NAME(GL_DIFFUSE), TYPE_8GLdouble, 4, -1, "1.1", STATE_LIGHT },
    { STATE_NAME(GL_SPECULAR), TYPE_8GLdouble, 4, -1, "1.1", STATE_LIGHT },
    { STATE_NAME(GL_POSITION), TYPE_8GLdouble, 4, -1, "1.1", STATE_LIGHT },
    { STATE_NAME(GL_CONSTANT_ATTENUATION), TYPE_8GLdouble, 1, -1, "1.1", STATE_LIGHT },
    { STATE_NAME(GL_LINEAR_ATTENUATION), TYPE_8GLdouble, 1, -1, "1.1", STATE_LIGHT },
    { STATE_NAME(GL_QUADRATIC_ATTENUATION), TYPE_8GLdouble, 1, -1, "1.1", STATE_LIGHT },
    { STATE_NAME(GL_SPOT_DIRECTION), TYPE_8GLdouble, 3, -1, "1.1", STATE_LIGHT },
    { STATE_NAME(GL_SPOT_EXPONENT), TYPE_8GLdouble, 1, -1, "1.1", STATE_LIGHT },
    { STATE_NAME(GL_SPOT_CUTOFF), TYPE_8GLdouble, 1, -1, "1.1", STATE_LIGHT },
    { NULL, GL_NONE, NULL_TYPE, 0, 0, NULL, 0 }
};

static const state_info material_state[] =
{
    { STATE_NAME(GL_AMBIENT), TYPE_8GLdouble, 4, -1, "1.1", STATE_MATERIAL },
    { STATE_NAME(GL_DIFFUSE), TYPE_8GLdouble, 4, -1, "1.1", STATE_MATERIAL },
    { STATE_NAME(GL_SPECULAR), TYPE_8GLdouble, 4, -1, "1.1", STATE_MATERIAL },
    { STATE_NAME(GL_EMISSION), TYPE_8GLdouble, 4, -1, "1.1", STATE_MATERIAL },
    { STATE_NAME(GL_SHININESS), TYPE_8GLdouble, 1, -1, "1.1", STATE_MATERIAL },
    { STATE_NAME(GL_COLOR_INDEXES), TYPE_8GLdouble, 3, -1, "1.1", STATE_MATERIAL },
    { NULL, GL_NONE, NULL_TYPE, 0, 0, NULL, 0 }
};

static const state_info color_table_parameter_state[] =
{
    { STATE_NAME(GL_COLOR_TABLE_FORMAT), TYPE_6GLenum, 1, BUGLE_GL_ARB_imaging, NULL, STATE_COLOR_TABLE_PARAMETER },
    { STATE_NAME(GL_COLOR_TABLE_WIDTH), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_COLOR_TABLE_PARAMETER },
    { STATE_NAME(GL_COLOR_TABLE_RED_SIZE), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_COLOR_TABLE_PARAMETER },
    { STATE_NAME(GL_COLOR_TABLE_GREEN_SIZE), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_COLOR_TABLE_PARAMETER },
    { STATE_NAME(GL_COLOR_TABLE_BLUE_SIZE), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_COLOR_TABLE_PARAMETER },
    { STATE_NAME(GL_COLOR_TABLE_ALPHA_SIZE), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_COLOR_TABLE_PARAMETER },
    { STATE_NAME(GL_COLOR_TABLE_LUMINANCE_SIZE), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_COLOR_TABLE_PARAMETER },
    { STATE_NAME(GL_COLOR_TABLE_INTENSITY_SIZE), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_COLOR_TABLE_PARAMETER },
    { STATE_NAME(GL_COLOR_TABLE_SCALE), TYPE_8GLdouble, 4, BUGLE_GL_ARB_imaging, NULL, STATE_COLOR_TABLE_PARAMETER | STATE_SELECT_NO_PROXY },
    { STATE_NAME(GL_COLOR_TABLE_BIAS), TYPE_8GLdouble, 4, BUGLE_GL_ARB_imaging, NULL, STATE_COLOR_TABLE_PARAMETER | STATE_SELECT_NO_PROXY },
    { NULL, GL_NONE, NULL_TYPE, 0, 0, NULL, 0 }
};

static const state_info convolution_parameter_state[] =
{
    { STATE_NAME(GL_CONVOLUTION_BORDER_COLOR), TYPE_8GLdouble, 4, BUGLE_GL_ARB_imaging, NULL, STATE_CONVOLUTION_PARAMETER },
    { STATE_NAME(GL_CONVOLUTION_BORDER_MODE), TYPE_6GLenum, 1, BUGLE_GL_ARB_imaging, NULL, STATE_CONVOLUTION_PARAMETER },
    { STATE_NAME(GL_CONVOLUTION_FILTER_SCALE), TYPE_8GLdouble, 4, BUGLE_GL_ARB_imaging, NULL, STATE_CONVOLUTION_PARAMETER },
    { STATE_NAME(GL_CONVOLUTION_FILTER_BIAS), TYPE_8GLdouble, 4, BUGLE_GL_ARB_imaging, NULL, STATE_CONVOLUTION_PARAMETER },
    { STATE_NAME(GL_CONVOLUTION_FORMAT), TYPE_6GLenum, 1, BUGLE_GL_ARB_imaging, NULL, STATE_CONVOLUTION_PARAMETER },
    { STATE_NAME(GL_CONVOLUTION_WIDTH), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_CONVOLUTION_PARAMETER },
    /* FIXME: CONVOLUTION_HEIGHT and CONVOLUTION_MAX_HEIGHT are illegal for CONVOLUTION_1D */
    { STATE_NAME(GL_CONVOLUTION_HEIGHT), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_CONVOLUTION_PARAMETER },
    { STATE_NAME(GL_MAX_CONVOLUTION_WIDTH), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_CONVOLUTION_PARAMETER },
    { STATE_NAME(GL_MAX_CONVOLUTION_HEIGHT), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_CONVOLUTION_PARAMETER },
    { NULL, GL_NONE, NULL_TYPE, 0, 0, NULL, 0 }
};

static const state_info histogram_parameter_state[] =
{
    { STATE_NAME(GL_HISTOGRAM_WIDTH), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_HISTOGRAM_PARAMETER },
    { STATE_NAME(GL_HISTOGRAM_FORMAT), TYPE_6GLenum, 1, BUGLE_GL_ARB_imaging, NULL, STATE_HISTOGRAM_PARAMETER },
    { STATE_NAME(GL_HISTOGRAM_RED_SIZE), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_HISTOGRAM_PARAMETER },
    { STATE_NAME(GL_HISTOGRAM_GREEN_SIZE), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_HISTOGRAM_PARAMETER },
    { STATE_NAME(GL_HISTOGRAM_BLUE_SIZE), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_HISTOGRAM_PARAMETER },
    { STATE_NAME(GL_HISTOGRAM_ALPHA_SIZE), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_HISTOGRAM_PARAMETER },
    { STATE_NAME(GL_HISTOGRAM_LUMINANCE_SIZE), TYPE_5GLint, 1, BUGLE_GL_ARB_imaging, NULL, STATE_HISTOGRAM_PARAMETER },
    { STATE_NAME(GL_HISTOGRAM_SINK), TYPE_9GLboolean, 1, BUGLE_GL_ARB_imaging, NULL, STATE_HISTOGRAM_PARAMETER },
    { NULL, GL_NONE, NULL_TYPE, 0, 0, NULL, 0 }
};

static const state_info minmax_parameter_state[] =
{
    { STATE_NAME(GL_MINMAX_FORMAT), TYPE_6GLenum, 1, BUGLE_GL_ARB_imaging, NULL, STATE_MINMAX_PARAMETER },
    { STATE_NAME(GL_MINMAX_SINK), TYPE_9GLboolean, 1, BUGLE_GL_ARB_imaging, NULL, STATE_MINMAX_PARAMETER },
    { NULL, GL_NONE, NULL_TYPE, 0, 0, NULL, 0 }
};

static const state_info vertex_attrib_state[] =
{
#ifdef GL_ARB_vertex_program
    { STATE_NAME_EXT(GL_VERTEX_ATTRIB_ARRAY_ENABLED, _ARB), TYPE_9GLboolean, 1, BUGLE_GL_ARB_vertex_program, "2.0", STATE_VERTEX_ATTRIB },
    { STATE_NAME_EXT(GL_VERTEX_ATTRIB_ARRAY_SIZE, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_vertex_program, "2.0", STATE_VERTEX_ATTRIB },
    { STATE_NAME_EXT(GL_VERTEX_ATTRIB_ARRAY_STRIDE, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_vertex_program, "2.0", STATE_VERTEX_ATTRIB },
    { STATE_NAME_EXT(GL_VERTEX_ATTRIB_ARRAY_TYPE, _ARB), TYPE_6GLenum, 1, BUGLE_GL_ARB_vertex_program, "2.0", STATE_VERTEX_ATTRIB },
    { STATE_NAME_EXT(GL_VERTEX_ATTRIB_ARRAY_NORMALIZED, _ARB), TYPE_9GLboolean, 1, BUGLE_GL_ARB_vertex_program, "2.0", STATE_VERTEX_ATTRIB },
    { STATE_NAME_EXT(GL_VERTEX_ATTRIB_ARRAY_POINTER, _ARB), TYPE_P6GLvoid, 1, BUGLE_GL_ARB_vertex_program, "2.0", STATE_VERTEX_ATTRIB },
    { STATE_NAME_EXT(GL_CURRENT_VERTEX_ATTRIB, _ARB), TYPE_8GLdouble, 4, BUGLE_GL_ARB_vertex_program, "2.0", STATE_VERTEX_ATTRIB | STATE_SELECT_NON_ZERO },
#endif
    { NULL, GL_NONE, NULL_TYPE, 0, 0, NULL, 0 }
};

static const state_info query_state[] =
{
#ifdef GL_ARB_occlusion_query
    { STATE_NAME_EXT(GL_CURRENT_QUERY, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_occlusion_query, "1.5", STATE_QUERY },
    { STATE_NAME_EXT(GL_QUERY_COUNTER_BITS, _ARB), TYPE_5GLint, 1, BUGLE_GL_ARB_occlusion_query, "1.5", STATE_QUERY },
#endif
    { NULL, GL_NONE, NULL_TYPE, 0, 0, NULL, 0 }
};

static const state_info query_object_state[] =
{
#ifdef GL_ARB_occlusion_query
    { STATE_NAME_EXT(GL_QUERY_RESULT, _ARB), TYPE_6GLuint, 1, BUGLE_GL_ARB_occlusion_query, "1.5", STATE_QUERY },
    { STATE_NAME_EXT(GL_QUERY_RESULT_AVAILABLE, _ARB), TYPE_9GLboolean, 1, BUGLE_GL_ARB_occlusion_query, "1.5", STATE_QUERY },
#endif
    { NULL, GL_NONE, NULL_TYPE, 0, 0, NULL, 0 }
};

typedef struct
{
    const char *name;
    GLenum token;
} enum_pair;

static const enum_pair material_pairs[] =
{
    { STATE_NAME(GL_FRONT) },
    { STATE_NAME(GL_BACK) },
    { NULL, GL_NONE }
};

static const enum_pair tex_gen_pairs[] =
{
    { STATE_NAME(GL_S) },
    { STATE_NAME(GL_T) },
    { STATE_NAME(GL_R) },
    { STATE_NAME(GL_Q) },
    { NULL, GL_NONE }
};

static const enum_pair color_table_parameter_pairs[] =
{
    { STATE_NAME(GL_COLOR_TABLE) },
    { STATE_NAME(GL_POST_CONVOLUTION_COLOR_TABLE) },
    { STATE_NAME(GL_POST_COLOR_MATRIX_COLOR_TABLE) },
    { STATE_NAME(GL_PROXY_COLOR_TABLE) },
    { STATE_NAME(GL_PROXY_POST_CONVOLUTION_COLOR_TABLE) },
    { STATE_NAME(GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE) },
    { NULL, GL_NONE }
};

static const enum_pair convolution_parameter_pairs[] =
{
    { STATE_NAME(GL_CONVOLUTION_1D) },
    { STATE_NAME(GL_CONVOLUTION_2D) },
    { NULL, GL_NONE }
};

static const enum_pair histogram_parameter_pairs[] =
{
    { STATE_NAME(GL_HISTOGRAM) },
    { STATE_NAME(GL_PROXY_HISTOGRAM) },
    { NULL, GL_NONE }
};

static const enum_pair minmax_parameter_pairs[] =
{
    { STATE_NAME(GL_MINMAX) },
    { NULL, GL_NONE }
};

static const enum_pair query_pairs[] =
{
#ifdef GL_ARB_occlusion_query
    { STATE_NAME_EXT(GL_SAMPLES_PASSED, _ARB) },
#endif
    { NULL, GL_NONE }
};

/* This exists to simplify the work of gldump.c */
const state_info * const all_state[] =
{
    global_state,
    tex_parameter_state,
    tex_level_parameter_state,
    tex_unit_state,
    tex_gen_state,
    light_state,
    material_state,
    color_table_parameter_state,
    convolution_parameter_state,
    histogram_parameter_state,
    minmax_parameter_state,
    vertex_attrib_state,
    query_state,
    query_object_state,
    NULL
};

typedef struct
{
    void *out;
    budgie_type type;
    int length;
} dump_wrapper_data;

static void dump_wrapper(FILE *f, void *data)
{
    const dump_wrapper_data *w;
    int length;

    w = (const dump_wrapper_data *) data;
    length = w->length;
    if (length == 1) length = -1;
    budgie_dump_any_type_extended(w->type, w->out, -1, length, NULL, f);
}

static void get_helper(const glstate *state,
                       GLdouble *d, GLfloat *f, GLint *i,
                       budgie_type *in_type,
                       budgie_function get_double,
                       budgie_function get_float,
                       budgie_function get_int)
{
    if (state->info->type == TYPE_8GLdouble && get_double != NULL_FUNCTION)
    {
        (*(void (*)(GLenum, GLenum, GLdouble *)) budgie_function_table[get_double].real)(state->target, state->info->pname, d);
        *in_type = TYPE_8GLdouble;
    }
    else if ((state->info->type == TYPE_8GLdouble || state->info->type == TYPE_7GLfloat)
        && get_float != NULL_FUNCTION)
    {
        (*(void (*)(GLenum, GLenum, GLfloat *)) budgie_function_table[get_float].real)(state->target, state->info->pname, f);
        *in_type = TYPE_7GLfloat;
    }
    else
    {
        (*(void (*)(GLenum, GLenum, GLint *)) budgie_function_table[get_int].real)(state->target, state->info->pname, i);
        *in_type = TYPE_5GLint;
    }
}

char *bugle_state_get_string(const glstate *state)
{
    const char *s;
    GLdouble d[16];
    GLfloat f[16];
    GLint i[16];
    GLuint ui[16];
    GLboolean b[16];
    GLvoid *p[16];
    void *in;
    budgie_type in_type;
    dump_wrapper_data wrapper;

    GLint old_texture;
    GLint old_unit, old_client_unit;
    bool flag_active_texture = false;
    GLenum pname;

    if (!state->info) return NULL;
    if (state->info->pname) pname = state->info->pname;
    else pname = state->target;

#ifdef GL_ARB_multitexture
    if ((state->info->flags & STATE_MULTIPLEX_ACTIVE_TEXTURE)
        && bugle_gl_has_extension(BUGLE_GL_ARB_multitexture))
    {
        CALL_glGetIntegerv(GL_ACTIVE_TEXTURE_ARB, &old_unit);
        CALL_glGetIntegerv(GL_CLIENT_ACTIVE_TEXTURE_ARB, &old_client_unit);
        CALL_glActiveTextureARB(state->unit);
        CALL_glClientActiveTextureARB(state->unit);
        flag_active_texture = true;
    }
#endif
    if (state->info->flags & STATE_MULTIPLEX_BIND_TEXTURE)
    {
        CALL_glGetIntegerv(state->binding, &old_texture);
        CALL_glBindTexture(state->target, state->object);
    }

    switch (state->info->flags & STATE_MODE_MASK)
    {
    case STATE_MODE_GLOBAL:
        if (state->info->type == TYPE_PKc)
        {
            s = (const char *) CALL_glGetString(pname);
            return bugle_strdup(s);
        }
        else if (state->info->type == TYPE_9GLboolean)
        {
            CALL_glGetBooleanv(pname, b);
            in_type = TYPE_9GLboolean;
        }
        else if (state->info->type == TYPE_P6GLvoid)
        {
            CALL_glGetPointerv(pname, p);
            in_type = TYPE_P6GLvoid;
        }
        else if (state->info->type == TYPE_8GLdouble)
        {
            CALL_glGetDoublev(pname, d);
            in_type = TYPE_8GLdouble;
        }
        else if (state->info->type == TYPE_7GLfloat)
        {
            CALL_glGetFloatv(pname, f);
            in_type = TYPE_7GLfloat;
        }
        else
        {
            CALL_glGetIntegerv(pname, i);
            in_type = TYPE_5GLint;
        }
        break;
    case STATE_MODE_ENABLED:
        b[0] = CALL_glIsEnabled(pname);
        in_type = TYPE_9GLboolean;
        break;
    case STATE_MODE_TEX_ENV:
        get_helper(state, d, f, i, &in_type, NULL_FUNCTION,
                   FUNC_glGetTexEnvfv, FUNC_glGetTexEnviv);
        break;
    case STATE_MODE_TEX_PARAMETER:
        get_helper(state, d, f, i, &in_type, NULL_FUNCTION,
                   FUNC_glGetTexParameterfv, FUNC_glGetTexParameteriv);
        break;
    case STATE_MODE_TEX_LEVEL_PARAMETER:
        if (state->info->type == TYPE_8GLdouble || state->info->type == TYPE_7GLfloat)
        {
            CALL_glGetTexLevelParameterfv(state->target, state->level, pname, f);
            in_type = TYPE_7GLfloat;
        }
        else
        {
            CALL_glGetTexLevelParameteriv(state->target, state->level, pname, i);
            in_type = TYPE_5GLint;
        }
        break;
    case STATE_MODE_TEX_GEN:
        get_helper(state, d, f, i, &in_type, FUNC_glGetTexGendv,
                   FUNC_glGetTexGenfv, FUNC_glGetTexGeniv);
        break;
    case STATE_MODE_LIGHT:
        get_helper(state, d, f, i, &in_type, NULL_FUNCTION,
                   FUNC_glGetLightfv, FUNC_glGetLightiv);
        break;
    case STATE_MODE_MATERIAL:
        get_helper(state, d, f, i, &in_type, NULL_FUNCTION,
                   FUNC_glGetMaterialfv, FUNC_glGetMaterialiv);
        break;
    case STATE_MODE_CLIP_PLANE:
        CALL_glGetClipPlane(state->target, d);
        in_type = TYPE_8GLdouble;
        break;
    case STATE_MODE_COLOR_TABLE_PARAMETER:
        get_helper(state, d, f, i, &in_type, NULL_FUNCTION,
                   FUNC_glGetColorTableParameterfv, FUNC_glGetColorTableParameteriv);
        break;
    case STATE_MODE_CONVOLUTION_PARAMETER:
        get_helper(state, d, f, i, &in_type, NULL_FUNCTION,
                   FUNC_glGetConvolutionParameterfv, FUNC_glGetConvolutionParameteriv);
        break;
    case STATE_MODE_HISTOGRAM_PARAMETER:
        get_helper(state, d, f, i, &in_type, NULL_FUNCTION,
                   FUNC_glGetHistogramParameterfv, FUNC_glGetHistogramParameteriv);
        break;
    case STATE_MODE_MINMAX_PARAMETER:
        get_helper(state, d, f, i, &in_type, NULL_FUNCTION,
                   FUNC_glGetMinmaxParameterfv, FUNC_glGetMinmaxParameteriv);
        break;
#ifdef GL_ARB_vertex_program
    case STATE_MODE_VERTEX_ATTRIB:
        if (state->info->type == TYPE_P6GLvoid)
        {
            CALL_glGetVertexAttribPointervARB(state->object, pname, p);
            in_type = TYPE_P6GLvoid;
        }
        else if (state->info->type == TYPE_8GLdouble)
        {
            CALL_glGetVertexAttribdvARB(state->object, pname, d);
            in_type = TYPE_8GLdouble;
        }
        else if (state->info->type == TYPE_7GLfloat)
        {
            CALL_glGetVertexAttribfvARB(state->object, pname, f);
            in_type = TYPE_7GLfloat;
        }
        else
        {
            CALL_glGetVertexAttribivARB(state->object, pname, i);
            in_type = TYPE_5GLint;
        }
        break;
#endif
#ifdef GL_ARB_occlusion_query
    case STATE_MODE_QUERY:
        CALL_glGetQueryivARB(state->target, pname, i);
        in_type = TYPE_5GLint;
        break;
    case STATE_MODE_QUERY_OBJECT:
        if (state->info->type == TYPE_6GLuint)
        {
            CALL_glGetQueryObjectuivARB(state->object, pname, ui);
            in_type = TYPE_6GLuint;
        }
        else
        {
            CALL_glGetQueryObjectivARB(state->object, pname, i);
            in_type = TYPE_5GLint;
        }
        break;
#endif
    default:
        abort();
    }

#ifdef GL_ARB_multitexture
    if (flag_active_texture)
    {
        CALL_glActiveTextureARB(old_unit);
        CALL_glClientActiveTextureARB(old_client_unit);
    }
#endif
    if (state->info->flags & STATE_MULTIPLEX_BIND_TEXTURE)
        CALL_glBindTexture(state->target, old_texture);

    switch (in_type)
    {
    case TYPE_8GLdouble: in = d; break;
    case TYPE_7GLfloat: in = f; break;
    case TYPE_5GLint: in = i; break;
    case TYPE_6GLuint: in = ui; break;
    case TYPE_9GLboolean: in = b; break;
    case TYPE_P6GLvoid: in = p; break;
    default: abort();
    }

    if (CALL_glGetError())
    {
        if (state->name)
            fprintf(stderr, "GL error generated by state %s\n", state->name);
        else
            fprintf(stderr, "GL error generated by anonymous state\n");
        return bugle_strdup("<GL error>");
    }

    wrapper.out = bugle_malloc(state->info->length * budgie_type_table[state->info->type].size);
    wrapper.type = state->info->type;
    wrapper.length = state->info->length;
    budgie_type_convert(wrapper.out, wrapper.type, in, in_type, wrapper.length);
    return budgie_string_io(dump_wrapper, &wrapper);
}

void bugle_state_get_children(const glstate *self, bugle_linked_list *children)
{
    if (self->spawn_children) (*self->spawn_children)(self, children);
    else bugle_list_init(children, true);
}

void bugle_state_clear(glstate *self)
{
    if (self->name) free(self->name);
}

/* All the make functions _append_ nodes to children. That means you have
 * to initialise the list yourself.
 */
static void make_leaves_conditional(const glstate *self, const state_info *table,
                                    unsigned int flags, unsigned int mask,
                                    bugle_linked_list *children)
{
    const char *version;
    glstate *child;
    const state_info *info;

    version = (const char *) CALL_glGetString(GL_VERSION);
    for (info = table; info->name; info++)
    {
        if ((info->flags & mask) == flags
            && ((info->version && strcmp(version, info->version) >= 0)
                || (info->extension != -1 && bugle_gl_has_extension(info->extension))))
        {
            child = bugle_malloc(sizeof(glstate));
            *child = *self; /* copies contextual info */
            child->name = bugle_strdup(info->name);
            child->info = info;
            child->spawn_children = NULL;
            bugle_list_append(children, child);
        }
    }
}

static void make_leaves(const glstate *self, const state_info *table,
                        bugle_linked_list *children)
{
    make_leaves_conditional(self, table, 0, 0, children);
}

static void make_fixed(const glstate *self,
                       const enum_pair *pairs,
                       size_t offset,
                       void (*spawn)(const glstate *, bugle_linked_list *),
                       bugle_linked_list *children)
{
    size_t i;
    glstate *child;

    for (i = 0; pairs[i].name; i++)
    {
        child = bugle_malloc(sizeof(glstate));
        *child = *self;
        child->info = NULL;
        child->name = bugle_strdup(pairs[i].name);
        *(GLenum *) (((char *) child) + offset) = pairs[i].token;
        child->spawn_children = spawn;
        bugle_list_append(children, child);
    }
}

static void make_counted(const glstate *self,
                         int count,
                         const char *format,
                         GLenum base,
                         size_t offset,
                         void (*spawn)(const glstate *, bugle_linked_list *),
                         const state_info *info,
                         bugle_linked_list *children)
{
    int i;
    glstate *child;

    for (i = 0; i < count; i++)
    {
        child = bugle_malloc(sizeof(glstate));
        *child = *self;
        child->info = info;
        bugle_asprintf(&child->name, format, i);
        *(GLenum *) (((char *) child) + offset) = base + i;
        child->spawn_children = spawn;
        bugle_list_append(children, child);
    }
}

static void make_object(const glstate *self,
                        const char *format,
                        GLuint id,
                        void (*spawn)(const glstate *, bugle_linked_list *),
                        const state_info *info,
                        bugle_linked_list *children)
{
    glstate *child;

    child = bugle_malloc(sizeof(glstate));
    *child = *self;
    child->info = info;
    bugle_asprintf(&child->name, format, id);
    child->object = id;
    child->spawn_children = spawn;
    bugle_list_append(children, child);
}

static void make_objects(const glstate *self,
                         bugle_trackobjects_type type,
                         bool add_zero,
                         const char *format,
                         void (*spawn_children)(const glstate *, bugle_linked_list *),
                         state_info *info,
                         bugle_linked_list *children)
{
    bugle_linked_list objects;
    bugle_list_node *i;
    bugle_trackobjects_id *id;

    if (add_zero)
        make_object(self, format, 0, spawn_children, info, children);
    bugle_trackobjects_get(type, &objects);
    for (i = bugle_list_head(&objects); i; i = bugle_list_next(i))
    {
        id = (bugle_trackobjects_id *) bugle_list_data(i);
        make_object(self, format, id->id, spawn_children, info, children);
    }
    bugle_list_clear(&objects);
}

static void spawn_children_tex_target(const glstate *, bugle_linked_list *);

static void make_tex_target(const glstate *self,
                            const char *name,
                            GLenum target,
                            GLenum binding,
                            bugle_linked_list *children)
{
    glstate *child;

    child = bugle_malloc(sizeof(glstate));
    *child = *self;
    child->name = bugle_strdup(name);
    child->target = target;
    child->binding = binding;
    child->spawn_children = spawn_children_tex_target;
    child->info = NULL;
    bugle_list_append(children, child);
}

static void spawn_children_tex_gen(const glstate *self, bugle_linked_list *children)
{
    bugle_list_init(children, true);
    make_leaves(self, tex_gen_state, children);
}

static void spawn_children_tex_unit(const glstate *self, bugle_linked_list *children)
{
    bugle_list_node *i;
    glstate *child;

    bugle_list_init(children, true);
    make_leaves(self, tex_unit_state, children);
    for (i = bugle_list_head(children); i; i = bugle_list_next(i))
    {
        child = (glstate *) bugle_list_data(i);
        if (child->info
            && (child->info->flags & STATE_MODE_MASK) == STATE_MODE_TEX_ENV)
        {
#ifdef GL_EXT_texture_lod_bias
            if (child->info->flags & STATE_FLAG_FILTER_CONTROL)
                child->target = GL_TEXTURE_FILTER_CONTROL;
            else
#endif
            {
                child->target = GL_TEXTURE_ENV;
            }
        }
    }
    make_fixed(self, tex_gen_pairs, offsetof(glstate, target),
               spawn_children_tex_gen, children);
}

static void spawn_children_tex_level_parameter(const glstate *self, bugle_linked_list *children)
{
    bugle_list_init(children, true);
    make_leaves(self, tex_level_parameter_state, children);
}

static GLint log2(GLint s)
{
    GLint ans = 0;

    if (s < 1) return -1;
    while (s > 1)
    {
        s = s / 2; /* rounding down is consistent with NPOT mipmaps */
        ans++;
    }
    return ans;
}

static void spawn_children_tex_parameter(const glstate *self, bugle_linked_list *children)
{
    GLint dim, log_dim;
    GLint p, q;       /* names follow GL 2.0 spec */
    GLint base, max, i;
    glstate *child;

    bugle_list_init(children, true);
    make_leaves(self, tex_parameter_state, children);
#ifdef GL_ARB_texture_cube_map
    if (self->target == GL_TEXTURE_CUBE_MAP_ARB) return; /* FIXME: cube faces */
#endif

    CALL_glGetTexParameteriv(self->target, GL_TEXTURE_BASE_LEVEL, &base);
    CALL_glGetTexParameteriv(self->target, GL_TEXTURE_MAX_LEVEL, &max);
    p = -1;
    switch (self->target)
    {
#ifdef GL_EXT_texture_3D
    case GL_TEXTURE_3D_EXT:
        CALL_glGetTexLevelParameteriv(self->target, base, GL_TEXTURE_DEPTH_EXT, &dim);
        log_dim = log2(dim);
        if (log_dim > p) p = log_dim;
        /* Fall through */
#endif
    case GL_TEXTURE_2D:
        CALL_glGetTexLevelParameteriv(self->target, base, GL_TEXTURE_HEIGHT, &dim);
        log_dim = log2(dim);
        if (log_dim > p) p = log_dim;
        /* Fall through */
    case GL_TEXTURE_1D:
        CALL_glGetTexLevelParameteriv(self->target, base, GL_TEXTURE_WIDTH, &dim);
        log_dim = log2(dim);
        if (log_dim > p) p = log_dim;
        break;
    }

    q = max;
    if (p < q) q = p;
    for (i = base; i <= base + q; i++)
    {
        child = bugle_malloc(sizeof(glstate));
        *child = *self;
        bugle_asprintf(&child->name, "level[%d]", (int) i);
        child->info = NULL;
        child->level = i;
        child->spawn_children = spawn_children_tex_level_parameter;
        bugle_list_append(children, child);
    }
}

static void spawn_children_tex_target(const glstate *self, bugle_linked_list *children)
{
    bugle_list_init(children, true);
    make_objects(self, BUGLE_TRACKOBJECTS_TEXTURE, true, "%d",
                 spawn_children_tex_parameter, NULL, children);
}

static void spawn_children_light(const glstate *self, bugle_linked_list *children)
{
    bugle_list_init(children, true);
    make_leaves(self, light_state, children);
}

static void spawn_children_material(const glstate *self, bugle_linked_list *children)
{
    bugle_list_init(children, true);
    make_leaves(self, material_state, children);
}

static void spawn_children_color_table_parameter(const glstate *self, bugle_linked_list *children)
{
    bugle_list_init(children, true);
    switch (self->target)
    {
    case GL_COLOR_TABLE:
    case GL_POST_CONVOLUTION_COLOR_TABLE:
    case GL_POST_COLOR_MATRIX_COLOR_TABLE:
        make_leaves(self, color_table_parameter_state, children);
        break;
    case GL_PROXY_COLOR_TABLE:
    case GL_PROXY_POST_CONVOLUTION_COLOR_TABLE:
    case GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE:
        make_leaves_conditional(self, color_table_parameter_state, 0,
                                STATE_SELECT_NO_PROXY, children);
        break;
    }
}

static void spawn_children_convolution_parameter(const glstate *self, bugle_linked_list *children)
{
    bugle_list_init(children, true);
    if (self->target == GL_CONVOLUTION_1D)
        make_leaves_conditional(self, convolution_parameter_state,
                                0, STATE_SELECT_NO_CONVOLUTION_1D, children);
    else
        make_leaves(self, convolution_parameter_state, children);
}

static void spawn_children_histogram_parameter(const glstate *self, bugle_linked_list *children)
{
    bugle_list_init(children, true);
    make_leaves(self, histogram_parameter_state, children);
}

static void spawn_children_minmax_parameter(const glstate *self, bugle_linked_list *children)
{
    bugle_list_init(children, true);
    make_leaves(self, minmax_parameter_state, children);
}

static void spawn_children_vertex_attrib(const glstate *self, bugle_linked_list *children)
{
    bugle_list_init(children, true);
    make_leaves_conditional(self, vertex_attrib_state,
                            0,
                            (self->object == 0) ? STATE_SELECT_NON_ZERO : 0,
                            children);
}

static void spawn_children_query(const glstate *self, bugle_linked_list *children)
{
    bugle_list_init(children, true);
    make_leaves(self, query_state, children);
}

static void spawn_children_query_object(const glstate *self, bugle_linked_list *children)
{
    bugle_list_init(children, true);
    make_leaves(self, query_object_state, children);
}

static void spawn_children_global(const glstate *self, bugle_linked_list *children)
{
    unsigned int mask = 0;

    static const state_info light_enable =
    {
        NULL, GL_NONE, TYPE_9GLboolean, 1, -1, "1.1", STATE_ENABLED
    };
    static const state_info clip_plane_state =
    {
        NULL, GL_NONE, TYPE_8GLdouble, 4, -1, "1.1", STATE_CLIP_PLANE
    };
#ifdef GL_ARB_draw_buffers
    static const state_info draw_buffers =
    {
        NULL, GL_NONE, TYPE_6GLenum, 1, BUGLE_GL_ARB_draw_buffers, "2.0", STATE_GLOBAL
    };
#endif
    GLint count, i;
    const char *version;

    version = (const char *) glGetString(GL_VERSION);
#ifdef GL_EXT_blend_func_separate
    if (bugle_gl_has_extension(BUGLE_GL_EXT_blend_func_separate)
        || strcmp(version, "1.4") >= 0)
        mask |= STATE_SELECT_NO_BLEND_FUNC_SEPARATE;
#endif
#ifdef GL_ARB_draw_buffers
    if (bugle_gl_has_extension(BUGLE_GL_ARB_draw_buffers)
        || strcmp(version, "2.0") >= 0)
        mask |= STATE_SELECT_NO_DRAW_BUFFERS;
#endif
    bugle_list_init(children, true);
    make_leaves_conditional(self, global_state,
                            0,
                            mask,
                            children);

#ifdef GL_ARB_multitexture
    if (bugle_gl_has_extension(BUGLE_GL_ARB_multitexture))
    {
        CALL_glGetIntegerv(GL_MAX_TEXTURE_UNITS_ARB, &count);
        make_counted(self, count, "GL_TEXTURE%d", GL_TEXTURE0_ARB,
                     offsetof(glstate, unit), spawn_children_tex_unit,
                     NULL, children);
    }
    else
#endif
    {
        make_leaves(self, tex_unit_state, children);
    }
    CALL_glGetIntegerv(GL_MAX_LIGHTS, &count);
    make_counted(self, count, "GL_LIGHT%d", GL_LIGHT0,
                 offsetof(glstate, target), spawn_children_light,
                 &light_enable, children);

    CALL_glGetIntegerv(GL_MAX_CLIP_PLANES, &count);
    make_counted(self, count, "GL_CLIP_PLANE%d", GL_CLIP_PLANE0,
                 offsetof(glstate, target), NULL,
                 &clip_plane_state, children);

#ifdef GL_ARB_draw_buffers
    if (bugle_gl_has_extension(BUGLE_GL_ARB_draw_buffers))
    {
        CALL_glGetIntegerv(GL_MAX_DRAW_BUFFERS_ARB, &count);
        make_counted(self, count, "GL_DRAW_BUFFER%d", GL_DRAW_BUFFER0_ARB,
                     offsetof(glstate, target), NULL,
                     &draw_buffers, children);
    }
    else
#endif

    make_fixed(self, material_pairs, offsetof(glstate, target),
               spawn_children_material, children);
    make_fixed(self, color_table_parameter_pairs, offsetof(glstate, target),
               spawn_children_color_table_parameter, children);
    make_fixed(self, convolution_parameter_pairs, offsetof(glstate, target),
               spawn_children_convolution_parameter, children);
    make_fixed(self, histogram_parameter_pairs, offsetof(glstate, target),
               spawn_children_histogram_parameter, children);
    make_fixed(self, minmax_parameter_pairs, offsetof(glstate, target),
               spawn_children_minmax_parameter, children);

#ifdef GL_ARB_vertex_program
    if (bugle_gl_has_extension(BUGLE_GL_ARB_vertex_program))
    {
        CALL_glGetIntegerv(GL_MAX_VERTEX_ATTRIBS_ARB, &count);
        for (i = 0; i < count; i++)
            make_object(self, "VertexAttrib[%d]", i, spawn_children_vertex_attrib, NULL, children);
    }
#endif

    /* FIXME: proxy objects */
    make_tex_target(self, "GL_TEXTURE_1D", GL_TEXTURE_1D,
                    GL_TEXTURE_BINDING_1D, children);
    make_tex_target(self, "GL_TEXTURE_2D", GL_TEXTURE_2D,
                    GL_TEXTURE_BINDING_2D, children);
#ifdef GL_VERSION_1_2
    if (strcmp(version, "1.2") >= 0)
        make_tex_target(self, "GL_TEXTURE_3D", GL_TEXTURE_3D,
                        GL_TEXTURE_BINDING_3D, children);
#endif
#ifdef GL_ARB_texture_cube_map
    if (bugle_gl_has_extension(BUGLE_GL_ARB_texture_cube_map))
        make_tex_target(self, "GL_TEXTURE_CUBE_MAP",
                        GL_TEXTURE_CUBE_MAP_ARB,
                        GL_TEXTURE_BINDING_CUBE_MAP_ARB,
                        children);
#endif

#ifdef GL_ARB_occlusion_query
    make_fixed(self, query_pairs, offsetof(glstate, target),
               spawn_children_query, children);
    if (bugle_gl_has_extension(BUGLE_GL_ARB_occlusion_query))
        make_objects(self, BUGLE_TRACKOBJECTS_QUERY, false, "Query[%d]",
                     spawn_children_query_object, NULL, children);
#endif
}

const glstate *bugle_state_get_root(void)
{
    static const glstate root =
    { "", GL_NONE, GL_NONE, GL_NONE, 0, 0, NULL, spawn_children_global };

    return &root;
}
