#!/usr/bin/env python
Import('env')

# TODO source scanner, make this a tool?
env.Command(
        'data/gl.tu',
        'data/gl.c',
        'CCACHE_DISABLE=1 $CC $_CPPINCFLAGS -fdump-translation-unit -c $SOURCE && ${srcdir.path}/mvtu.sh gl.c $TARGET')

bugleutils_list = env.SharedLibrary(
        'bugleutils',
        [
            'gl/gltypes.c',
            'apireflect.c',
            'glwin/glwintypes.c',
            '../common/misc.c',
            '../common/protocol.c',
            '../common/protocol-win32.c',
            '../common/hashtable.c',
            '../common/linkedlist.c',
            '../budgielib/internal.c',
            '../budgielib/reflect.c',
            '../budgielib/tables.c',
            'apitables.c'
        ])

env.SharedLibrary(
        'bugle',
        [
            env.CFile('confparse.y', YACCFLAGS = '-d')[0],
            'conflex.l',
            'interceptor.c',
            'dlopen.c',
            'filters.c',
            'stats.c',
            'statslex.l',
            env.CFile('statsparse.y', YACCFLAGS = '-d')[0],
            'log.c',
            'objects.c',
            'input.c',
            '../budgielib/addresses.c',
            'gl/glutils.c',
            'gl/glsl.c',
            'glwin/trackcontext.c',
            'gl/gldisplaylist.c',
            'gl/globjects.c',
            'gl/glextensions.c',
            'gl/glbeginend.c'
        ],
        LIBS = bugleutils_list[0])
