#!/usr/bin/env python

Import('envs', 'srcdir', 'builddir', 'libbugle', 'libbugleutils')

filter_env = envs['host'].Clone(
        LIBS = libbugle + libbugleutils,
        SHLIBPREFIX = '')

if filter_env['PLATFORM'] == 'posix' and 'gcc' in filter_env['TOOLS']:
    filter_env.Append(LINKFLAGS = '-Wl,-soname,${TARGET.file}')

for filter in [
        'checks',
        'common',
        'debugger',
        'exe',
        'extoverride',
        'logstats',
        'modify',
        'showextensions',
        'showstats',
        'stats_basic',
        'stats_calls',
        'stats_calltimes',
        'stats_fragments',
        'stats_nv',
        'stats_primitives',
        'trace',
        'unwindstack',
        'validate']:
    filter_env.LoadableModule(filter, [filter + '.c'])

filter_env.LoadableModule('eps', ['eps.c', '../gl2ps/gl2ps.c'])
