#!/usr/bin/env python
env = Environment(
        CPPPATH = ['#source/include', '#source'],
        CXXFLAGS = '-Wall -g',
        YACCHXXFILESUFFIX = '.h',
        topbuilddir = Dir('#build'),
        topsrcdir = Dir('.').srcnode(),
        tools = ['default', 'budgie', 'gengl']
        )
Export('env')
env.Append(BCPATH = [env['topbuilddir'], env['topsrcdir']])

SConscript('budgie/SConscript')
SConscript('src/SConscript')

budgie_outputs = [
        'include/budgie/call.h',
        'include/budgie/types2.h',
        'budgielib/defines.h',
        'budgielib/tables.c',
        'budgielib/lib.c'
        ]

env.Budgie(budgie_outputs, ['src/data/gl.tu', 'bc/gl-glx.bc'])

headers = ['GL/gl.h', 'GL/glext.h', 'GL/glx.h', 'GL/glxext.h']
headers = [env['find_header'](env, h) for h in headers]
# TODO change to bc/alias.bc
env.BudgieAlias(target = ['bc/gl/alias.bc'], source = headers)
