#!/usr/bin/env python

Import('aspects')

for dir in [
        'bugle',
        'bugle/gl',
        'bugle/glwin',
        'bugle/egl',
        'bugle/glx',
        'bugle/wgl',
        'budgie']:
    Install(aspects['includedir'] + '/' + dir, source = Glob(dir + '/*.h'))
Alias('install', aspects['includedir'])
